// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_api.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  Map<String, bool> dco_decode_Map_String_bool_None(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  BlockData dco_decode_block_data(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  FolderData dco_decode_box_autoadd_folder_data(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  NoteData dco_decode_box_autoadd_note_data(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_usize(dynamic raw);

  @protected
  VaultEncryptedDataFfi dco_decode_box_autoadd_vault_encrypted_data_ffi(
    dynamic raw,
  );

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FolderData dco_decode_folder_data(dynamic raw);

  @protected
  HealthCheckResult dco_decode_health_check_result(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<BlockData> dco_decode_list_block_data(dynamic raw);

  @protected
  List<FolderData> dco_decode_list_folder_data(dynamic raw);

  @protected
  List<NoteData> dco_decode_list_note_data(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, bool)> dco_decode_list_record_string_bool(dynamic raw);

  @protected
  List<SearchResult> dco_decode_list_search_result(dynamic raw);

  @protected
  List<TagData> dco_decode_list_tag_data(dynamic raw);

  @protected
  List<TranscriptSegmentFfi> dco_decode_list_transcript_segment_ffi(
    dynamic raw,
  );

  @protected
  MathRecognitionResultFfi dco_decode_math_recognition_result_ffi(dynamic raw);

  @protected
  MergeResult dco_decode_merge_result(dynamic raw);

  @protected
  NoteData dco_decode_note_data(dynamic raw);

  @protected
  OcrResultFfi dco_decode_ocr_result_ffi(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  FolderData? dco_decode_opt_box_autoadd_folder_data(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  NoteData? dco_decode_opt_box_autoadd_note_data(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_usize(dynamic raw);

  @protected
  (String, bool) dco_decode_record_string_bool(dynamic raw);

  @protected
  SearchResult dco_decode_search_result(dynamic raw);

  @protected
  SyncStatusData dco_decode_sync_status_data(dynamic raw);

  @protected
  TagData dco_decode_tag_data(dynamic raw);

  @protected
  TranscribeResultFfi dco_decode_transcribe_result_ffi(dynamic raw);

  @protected
  TranscriptSegmentFfi dco_decode_transcript_segment_ffi(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  VaultEncryptedDataFfi dco_decode_vault_encrypted_data_ffi(dynamic raw);

  @protected
  VersionInfo dco_decode_version_info(dynamic raw);

  @protected
  Map<String, bool> sse_decode_Map_String_bool_None(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  BlockData sse_decode_block_data(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  FolderData sse_decode_box_autoadd_folder_data(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  NoteData sse_decode_box_autoadd_note_data(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_usize(SseDeserializer deserializer);

  @protected
  VaultEncryptedDataFfi sse_decode_box_autoadd_vault_encrypted_data_ffi(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FolderData sse_decode_folder_data(SseDeserializer deserializer);

  @protected
  HealthCheckResult sse_decode_health_check_result(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<BlockData> sse_decode_list_block_data(SseDeserializer deserializer);

  @protected
  List<FolderData> sse_decode_list_folder_data(SseDeserializer deserializer);

  @protected
  List<NoteData> sse_decode_list_note_data(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, bool)> sse_decode_list_record_string_bool(
    SseDeserializer deserializer,
  );

  @protected
  List<SearchResult> sse_decode_list_search_result(
    SseDeserializer deserializer,
  );

  @protected
  List<TagData> sse_decode_list_tag_data(SseDeserializer deserializer);

  @protected
  List<TranscriptSegmentFfi> sse_decode_list_transcript_segment_ffi(
    SseDeserializer deserializer,
  );

  @protected
  MathRecognitionResultFfi sse_decode_math_recognition_result_ffi(
    SseDeserializer deserializer,
  );

  @protected
  MergeResult sse_decode_merge_result(SseDeserializer deserializer);

  @protected
  NoteData sse_decode_note_data(SseDeserializer deserializer);

  @protected
  OcrResultFfi sse_decode_ocr_result_ffi(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  FolderData? sse_decode_opt_box_autoadd_folder_data(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  NoteData? sse_decode_opt_box_autoadd_note_data(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_usize(SseDeserializer deserializer);

  @protected
  (String, bool) sse_decode_record_string_bool(SseDeserializer deserializer);

  @protected
  SearchResult sse_decode_search_result(SseDeserializer deserializer);

  @protected
  SyncStatusData sse_decode_sync_status_data(SseDeserializer deserializer);

  @protected
  TagData sse_decode_tag_data(SseDeserializer deserializer);

  @protected
  TranscribeResultFfi sse_decode_transcribe_result_ffi(
    SseDeserializer deserializer,
  );

  @protected
  TranscriptSegmentFfi sse_decode_transcript_segment_ffi(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  VaultEncryptedDataFfi sse_decode_vault_encrypted_data_ffi(
    SseDeserializer deserializer,
  );

  @protected
  VersionInfo sse_decode_version_info(SseDeserializer deserializer);

  @protected
  void sse_encode_Map_String_bool_None(
    Map<String, bool> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_block_data(BlockData self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_folder_data(
    FolderData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_note_data(
    NoteData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_vault_encrypted_data_ffi(
    VaultEncryptedDataFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_folder_data(FolderData self, SseSerializer serializer);

  @protected
  void sse_encode_health_check_result(
    HealthCheckResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_block_data(
    List<BlockData> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_folder_data(
    List<FolderData> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_note_data(List<NoteData> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_bool(
    List<(String, bool)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_search_result(
    List<SearchResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_tag_data(List<TagData> self, SseSerializer serializer);

  @protected
  void sse_encode_list_transcript_segment_ffi(
    List<TranscriptSegmentFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_math_recognition_result_ffi(
    MathRecognitionResultFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_merge_result(MergeResult self, SseSerializer serializer);

  @protected
  void sse_encode_note_data(NoteData self, SseSerializer serializer);

  @protected
  void sse_encode_ocr_result_ffi(OcrResultFfi self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_folder_data(
    FolderData? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_note_data(
    NoteData? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_usize(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_bool(
    (String, bool) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_search_result(SearchResult self, SseSerializer serializer);

  @protected
  void sse_encode_sync_status_data(
    SyncStatusData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_tag_data(TagData self, SseSerializer serializer);

  @protected
  void sse_encode_transcribe_result_ffi(
    TranscribeResultFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_transcript_segment_ffi(
    TranscriptSegmentFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_vault_encrypted_data_ffi(
    VaultEncryptedDataFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_version_info(VersionInfo self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
