// AUTO-GENERATED BY flutter_rust_bridge v2 — Web 平台实现 (WASM)
//
// 此文件由 `flutter_rust_bridge_codegen generate` 自动生成。
// 当前项目 flutter_rust_bridge.yaml 中 web: false，此文件为占位。

import 'frb_generated.dart';

/// Web 平台初始化实现（当前禁用）
Future<void> initImpl(RustLib rustLib) async {
  throw UnsupportedError('Web platform is not enabled. Set web: true in flutter_rust_bridge.yaml');
}
