// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `alloc_handle`, `block_editor_mut`, `canvas_engine_mut`, `canvas_engine`, `database_engine`, `empty`, `extract_content`, `flashcard_engine_mut`, `flashcard_engine`, `graph_engine`, `insert_engine`, `note_repo_mut`, `note_repo`, `note_to_data`, `open_connection_with_pragmas`, `search_engine_mut`, `search_engine`, `sync_engine_mut`, `sync_engine`, `with_engine_read`, `with_engine`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DatabaseViewData`, `EngineRegistry`, `InkStrokeFfi`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// 移除引擎实例（释放资源）
Future<void> dropEngine({required BigInt handle}) =>
    RustLib.instance.api.crateFrbApiDropEngine(handle: handle);

/// 获取当前活跃引擎句柄的数量
Future<BigInt> engineCount() => RustLib.instance.api.crateFrbApiEngineCount();

/// 初始化所有引擎 —— 替代原 devnote_init + register_all_handlers
/// FRB 自动生成 Dart: `Future<int> initEngines()`
///
/// P0 架构修复: 返回 engine_handle (u64)，实现基于句柄的依赖注入。
/// 支持多工作区 / 多用户场景，每个工作区拥有独立的引擎实例。
/// Dart 端应保存返回的句柄，后续所有 API 调用均需传入该句柄。
///
/// P0 修复: 原实现使用 `in_memory()`，FFI 模式下数据重启全部丢失。
/// 现改为文件持久化，数据库路径通过参数传入，与 Dart 端共享 `devnote.db`。
///
/// P0 修复: 原实现中 search/database/object/graph/flashcard 引擎初始化失败时
/// 用 `if let Ok` 静默吞错，用户无法感知功能受限。现改为收集失败引擎名并记录
/// 到 init_warnings，通过 health_check() 暴露给 Dart 端，由 UI 提示用户
/// "核心引擎未加载，功能受限"。
Future<BigInt> initEngines({required String dbPath}) =>
    RustLib.instance.api.crateFrbApiInitEngines(dbPath: dbPath);

/// 版本协商 —— 替代原 SystemEvent.GetVersion
Future<VersionInfo> getVersion({required BigInt engineHandle}) =>
    RustLib.instance.api.crateFrbApiGetVersion(engineHandle: engineHandle);

/// 健康检查 —— 替代原 SystemEvent.HealthCheck
Future<HealthCheckResult> healthCheck({required BigInt engineHandle}) =>
    RustLib.instance.api.crateFrbApiHealthCheck(engineHandle: engineHandle);

/// 创建笔记 —— 替代原 NoteEvent.CreateNote
Future<NoteData> createNote({
  required BigInt engineHandle,
  required String title,
  required String content,
  required String folderId,
}) => RustLib.instance.api.crateFrbApiCreateNote(
  engineHandle: engineHandle,
  title: title,
  content: content,
  folderId: folderId,
);

/// 获取笔记 —— 替代原 NoteEvent.GetNote
Future<NoteData?> getNote({required BigInt engineHandle, required String id}) =>
    RustLib.instance.api.crateFrbApiGetNote(engineHandle: engineHandle, id: id);

/// 更新笔记 —— 替代原 NoteEvent.UpdateNote
Future<NoteData> updateNote({
  required BigInt engineHandle,
  required String id,
  required String title,
  required String content,
}) => RustLib.instance.api.crateFrbApiUpdateNote(
  engineHandle: engineHandle,
  id: id,
  title: title,
  content: content,
);

/// 删除笔记 —— 替代原 NoteEvent.DeleteNote
Future<void> deleteNote({required BigInt engineHandle, required String id}) =>
    RustLib.instance.api.crateFrbApiDeleteNote(
      engineHandle: engineHandle,
      id: id,
    );

/// 列出笔记 —— 替代原 NoteEvent.ListNotes
Future<List<NoteData>> listNotes({
  required BigInt engineHandle,
  required String folderId,
}) => RustLib.instance.api.crateFrbApiListNotes(
  engineHandle: engineHandle,
  folderId: folderId,
);

/// 创建文件夹 —— 替代原 FolderEvent.CreateFolder
Future<FolderData> createFolder({
  required BigInt engineHandle,
  required String name,
  String? parentId,
}) => RustLib.instance.api.crateFrbApiCreateFolder(
  engineHandle: engineHandle,
  name: name,
  parentId: parentId,
);

/// 列出文件夹 —— 替代原 FolderEvent.ListFolders
Future<List<FolderData>> listFolders({
  required BigInt engineHandle,
  String? parentId,
}) => RustLib.instance.api.crateFrbApiListFolders(
  engineHandle: engineHandle,
  parentId: parentId,
);

/// 删除文件夹 —— 替代原 FolderEvent.DeleteFolder
Future<void> deleteFolder({required BigInt engineHandle, required String id}) =>
    RustLib.instance.api.crateFrbApiDeleteFolder(
      engineHandle: engineHandle,
      id: id,
    );

/// 获取文件夹 —— 替代原 FolderEvent.GetFolder
Future<FolderData?> getFolder({
  required BigInt engineHandle,
  required String id,
}) => RustLib.instance.api.crateFrbApiGetFolder(
  engineHandle: engineHandle,
  id: id,
);

/// 更新文件夹 —— 替代原 FolderEvent.UpdateFolder
Future<FolderData> updateFolder({
  required BigInt engineHandle,
  required String id,
  required String name,
  String? parentId,
  int? sortOrder,
}) => RustLib.instance.api.crateFrbApiUpdateFolder(
  engineHandle: engineHandle,
  id: id,
  name: name,
  parentId: parentId,
  sortOrder: sortOrder,
);

/// 创建标签 —— 替代原 TagEvent.CreateTag
Future<TagData> createTag({
  required BigInt engineHandle,
  required String name,
}) => RustLib.instance.api.crateFrbApiCreateTag(
  engineHandle: engineHandle,
  name: name,
);

/// 列出标签 —— 替代原 TagEvent.ListTags
Future<List<TagData>> listTags({required BigInt engineHandle}) =>
    RustLib.instance.api.crateFrbApiListTags(engineHandle: engineHandle);

/// 删除标签 —— 替代原 TagEvent.DeleteTag
Future<void> deleteTag({required BigInt engineHandle, required String id}) =>
    RustLib.instance.api.crateFrbApiDeleteTag(
      engineHandle: engineHandle,
      id: id,
    );

/// 按标签查询笔记 ID —— P1-2 修复: 消除双重持久化
///
/// 原实现: Flutter 端直接查询 Dart sqflite 的 note_tags 表，绕过 Rust FFI。
/// 现改为: 通过 FFI 调用 Rust 持久化层，确保数据源唯一。
Future<List<String>> getNoteIdsByTag({
  required BigInt engineHandle,
  required String tagId,
}) => RustLib.instance.api.crateFrbApiGetNoteIdsByTag(
  engineHandle: engineHandle,
  tagId: tagId,
);

/// 插入块 —— 替代原 EditorEvent.InsertBlock
Future<BlockData> insertBlock({
  required BigInt engineHandle,
  required String noteId,
  required String blockType,
  required String content,
  BigInt? position,
}) => RustLib.instance.api.crateFrbApiInsertBlock(
  engineHandle: engineHandle,
  noteId: noteId,
  blockType: blockType,
  content: content,
  position: position,
);

/// 更新块 —— 替代原 EditorEvent.UpdateBlock
Future<void> updateBlock({
  required BigInt engineHandle,
  required String id,
  required String content,
}) => RustLib.instance.api.crateFrbApiUpdateBlock(
  engineHandle: engineHandle,
  id: id,
  content: content,
);

/// 删除块 —— 替代原 EditorEvent.DeleteBlock
Future<void> deleteBlock({required BigInt engineHandle, required String id}) =>
    RustLib.instance.api.crateFrbApiDeleteBlock(
      engineHandle: engineHandle,
      id: id,
    );

/// 获取笔记的所有块 —— 替代原 EditorEvent.GetBlocks
Future<List<BlockData>> getBlocks({
  required BigInt engineHandle,
  required String noteId,
}) => RustLib.instance.api.crateFrbApiGetBlocks(
  engineHandle: engineHandle,
  noteId: noteId,
);

/// P1 架构修复 (3.3): 补齐 FFI block API
/// 获取单个 block by ID
Future<BlockData?> getBlock({
  required BigInt engineHandle,
  required String id,
}) => RustLib.instance.api.crateFrbApiGetBlock(
  engineHandle: engineHandle,
  id: id,
);

/// P1 架构修复 (3.3): 补齐 FFI block API，完成双持久化迁移
/// 移动块到新位置，自动重排其他块的 position
Future<void> moveBlock({
  required BigInt engineHandle,
  required String id,
  required BigInt newPosition,
}) => RustLib.instance.api.crateFrbApiMoveBlock(
  engineHandle: engineHandle,
  id: id,
  newPosition: newPosition,
);

/// P1 架构修复 (3.3): 补齐 FFI block API
/// 更新块类型
Future<void> updateBlockType({
  required BigInt engineHandle,
  required String id,
  required String blockType,
}) => RustLib.instance.api.crateFrbApiUpdateBlockType(
  engineHandle: engineHandle,
  id: id,
  blockType: blockType,
);

/// P1 架构修复 (3.3): 补齐 FFI block API
/// 批量替换指定笔记的所有块（原子替换）
Future<List<BlockData>> replaceBlocks({
  required BigInt engineHandle,
  required String noteId,
  required List<BlockData> blocks,
}) => RustLib.instance.api.crateFrbApiReplaceBlocks(
  engineHandle: engineHandle,
  noteId: noteId,
  blocks: blocks,
);

/// 搜索笔记 —— 替代原 SearchEvent.Search
Future<List<SearchResult>> searchNotes({
  required BigInt engineHandle,
  required String query,
  BigInt? limit,
  BigInt? offset,
}) => RustLib.instance.api.crateFrbApiSearchNotes(
  engineHandle: engineHandle,
  query: query,
  limit: limit,
  offset: offset,
);

/// 加密数据 —— 替代原 CryptoEvent.Encrypt
Future<String> encrypt({
  required BigInt engineHandle,
  required String plaintextBase64,
  required String keyBase64,
}) => RustLib.instance.api.crateFrbApiEncrypt(
  engineHandle: engineHandle,
  plaintextBase64: plaintextBase64,
  keyBase64: keyBase64,
);

/// 解密数据 —— 替代原 CryptoEvent.Decrypt
Future<String> decrypt({
  required BigInt engineHandle,
  required String ciphertextBase64,
  required String keyBase64,
}) => RustLib.instance.api.crateFrbApiDecrypt(
  engineHandle: engineHandle,
  ciphertextBase64: ciphertextBase64,
  keyBase64: keyBase64,
);

/// 派生密钥 —— 替代原 CryptoEvent.DeriveKey
Future<String> deriveKey({
  required BigInt engineHandle,
  required String password,
  required String saltBase64,
}) => RustLib.instance.api.crateFrbApiDeriveKey(
  engineHandle: engineHandle,
  password: password,
  saltBase64: saltBase64,
);

/// 推送变更 —— 替代原 SyncEvent.PushChanges
Future<SyncStatusData> pushChanges({required BigInt engineHandle}) =>
    RustLib.instance.api.crateFrbApiPushChanges(engineHandle: engineHandle);

/// 拉取变更 —— 替代原 SyncEvent.PullChanges
Future<SyncStatusData> pullChanges({required BigInt engineHandle}) =>
    RustLib.instance.api.crateFrbApiPullChanges(engineHandle: engineHandle);

/// 获取同步状态 —— 替代原 SyncEvent.GetStatus
Future<SyncStatusData> getSyncStatus({required BigInt engineHandle}) =>
    RustLib.instance.api.crateFrbApiGetSyncStatus(engineHandle: engineHandle);

/// 添加画布节点 —— 替代原 CanvasEvent.AddNode
Future<void> canvasAddNode({
  required BigInt engineHandle,
  required String canvasId,
  required String nodeJson,
}) => RustLib.instance.api.crateFrbApiCanvasAddNode(
  engineHandle: engineHandle,
  canvasId: canvasId,
  nodeJson: nodeJson,
);

/// 移除画布节点 —— 替代原 CanvasEvent.RemoveNode
Future<void> canvasRemoveNode({
  required BigInt engineHandle,
  required String canvasId,
  required String nodeId,
}) => RustLib.instance.api.crateFrbApiCanvasRemoveNode(
  engineHandle: engineHandle,
  canvasId: canvasId,
  nodeId: nodeId,
);

/// 画布自动布局 —— 替代原 CanvasEvent.AutoLayout
Future<void> canvasAutoLayout({
  required BigInt engineHandle,
  required String canvasId,
  required String layoutType,
}) => RustLib.instance.api.crateFrbApiCanvasAutoLayout(
  engineHandle: engineHandle,
  canvasId: canvasId,
  layoutType: layoutType,
);

/// 添加画布边 —— 替代原 CanvasEvent.AddEdge
Future<void> canvasAddEdge({
  required BigInt engineHandle,
  required String canvasId,
  required String edgeJson,
}) => RustLib.instance.api.crateFrbApiCanvasAddEdge(
  engineHandle: engineHandle,
  canvasId: canvasId,
  edgeJson: edgeJson,
);

/// 保存画布为 JSON —— 替代原 CanvasEvent.SaveJson
Future<void> canvasSaveCanvas({
  required BigInt engineHandle,
  required String canvasId,
  required String path,
}) => RustLib.instance.api.crateFrbApiCanvasSaveCanvas(
  engineHandle: engineHandle,
  canvasId: canvasId,
  path: path,
);

/// 从 JSON 加载画布 —— 替代原 CanvasEvent.LoadJson
Future<String> canvasLoadCanvas({
  required BigInt engineHandle,
  required String path,
}) => RustLib.instance.api.crateFrbApiCanvasLoadCanvas(
  engineHandle: engineHandle,
  path: path,
);

/// 创建数据库 —— 替代原 DatabaseEvent.CreateDatabase
Future<String> createDatabase({
  required BigInt engineHandle,
  required String name,
}) => RustLib.instance.api.crateFrbApiCreateDatabase(
  engineHandle: engineHandle,
  name: name,
);

/// 评估公式 —— 替代原 DatabaseEvent.EvaluateFormula
///
/// 返回 JSON 序列化的结果字符串，避免 FRB 对 serde_json::Value 的 opaque 类型处理。
/// 调用方可用 dart:convert jsonDecode 解析。
Future<String> evaluateFormula({
  required String formula,
  required String rowValues,
  required String allRows,
}) => RustLib.instance.api.crateFrbApiEvaluateFormula(
  formula: formula,
  rowValues: rowValues,
  allRows: allRows,
);

/// 添加数据库视图 —— 替代原 DatabaseEvent.AddView
Future<String> databaseAddView({
  required BigInt engineHandle,
  required String dbId,
  required String name,
  required String viewType,
}) => RustLib.instance.api.crateFrbApiDatabaseAddView(
  engineHandle: engineHandle,
  dbId: dbId,
  name: name,
  viewType: viewType,
);

/// 查询数据库行 —— 替代原 DatabaseEvent.QueryRows
Future<String> databaseQueryRows({
  required BigInt engineHandle,
  required String dbId,
}) => RustLib.instance.api.crateFrbApiDatabaseQueryRows(
  engineHandle: engineHandle,
  dbId: dbId,
);

/// 计算中心性 —— 替代原 GraphEvent.CalculateCentrality
Future<String> calculateCentrality({required BigInt engineHandle}) => RustLib
    .instance
    .api
    .crateFrbApiCalculateCentrality(engineHandle: engineHandle);

/// 检测聚类 —— 替代原 GraphEvent.DetectClusters
Future<String> detectClusters({required BigInt engineHandle}) =>
    RustLib.instance.api.crateFrbApiDetectClusters(engineHandle: engineHandle);

/// 创建卡组 —— 替代原 FlashcardEvent.CreateDeck
Future<String> createDeck({
  required BigInt engineHandle,
  required String name,
  required String description,
}) => RustLib.instance.api.crateFrbApiCreateDeck(
  engineHandle: engineHandle,
  name: name,
  description: description,
);

/// 复习卡片 —— 替代原 FlashcardEvent.ReviewCard
Future<String> reviewFlashcard({
  required BigInt engineHandle,
  required String flashcardId,
  required int quality,
}) => RustLib.instance.api.crateFrbApiReviewFlashcard(
  engineHandle: engineHandle,
  flashcardId: flashcardId,
  quality: quality,
);

/// 获取待复习卡片 —— 替代原 FlashcardEvent.GetDueCards
Future<String> getDueCards({
  required BigInt engineHandle,
  required String deckId,
  BigInt? limit,
}) => RustLib.instance.api.crateFrbApiGetDueCards(
  engineHandle: engineHandle,
  deckId: deckId,
  limit: limit,
);

/// CRDT 合并 —— 替代原 CRDTEvent.Merge
Future<MergeResult> crdtMerge({
  required BigInt engineHandle,
  required String docId,
  required String deviceId,
  required String remoteOpsJson,
}) => RustLib.instance.api.crateFrbApiCrdtMerge(
  engineHandle: engineHandle,
  docId: docId,
  deviceId: deviceId,
  remoteOpsJson: remoteOpsJson,
);

/// 导入 Markdown —— 替代原 FormatEvent.ImportMarkdown
Future<String> importMarkdown({required String path}) =>
    RustLib.instance.api.crateFrbApiImportMarkdown(path: path);

/// 导出 Markdown —— 替代原 FormatEvent.ExportMarkdown
Future<void> exportMarkdown({
  required String notesJson,
  required String path,
}) => RustLib.instance.api.crateFrbApiExportMarkdown(
  notesJson: notesJson,
  path: path,
);

/// 语音转文字 —— 集成 whisper-rs 进行本地语音转文字
///
/// 当前为接口框架，实际转写逻辑待 whisper-rs 集成后实现。
/// 调用方应捕获返回的 Err 并降级为平台原生 API。
Future<TranscribeResultFfi> transcribeAudio({
  required String audioBase64,
  required String lang,
}) => RustLib.instance.api.crateFrbApiTranscribeAudio(
  audioBase64: audioBase64,
  lang: lang,
);

/// OCR 识别图片中的文字 —— 替代原 OcrEvent.Recognize
/// image_base64: base64 编码的图片数据（支持 PNG/JPEG/WebP）
/// 返回识别出的全文
Future<String> ocrRecognizeImage({required String imageBase64}) =>
    RustLib.instance.api.crateFrbApiOcrRecognizeImage(imageBase64: imageBase64);

/// OCR 识别并返回结构化结果（含按行分割与置信度）
Future<OcrResultFfi> ocrRecognizeImageDetailed({required String imageBase64}) =>
    RustLib.instance.api.crateFrbApiOcrRecognizeImageDetailed(
      imageBase64: imageBase64,
    );

/// 将 OCR 识别文本纳入笔记的全文搜索索引 —— 替代原 OcrEvent.IndexImage
/// 将 OCR 文本追加到笔记现有内容后重新索引，使图片中的文字可被全文检索
Future<void> indexOcrText({
  required BigInt engineHandle,
  required String noteId,
  required String ocrText,
}) => RustLib.instance.api.crateFrbApiIndexOcrText(
  engineHandle: engineHandle,
  noteId: noteId,
  ocrText: ocrText,
);

/// Vault 加密 —— 使用用户密码对明文进行加密
/// 采用 Argon2id 密钥派生 + XChaCha20-Poly1305 加密
Future<VaultEncryptedDataFfi> vaultEncrypt({
  required String password,
  required String plaintext,
}) => RustLib.instance.api.crateFrbApiVaultEncrypt(
  password: password,
  plaintext: plaintext,
);

/// Vault 解密 —— 使用用户密码对密文进行解密
Future<String> vaultDecrypt({
  required String password,
  required VaultEncryptedDataFfi encrypted,
}) => RustLib.instance.api.crateFrbApiVaultDecrypt(
  password: password,
  encrypted: encrypted,
);

/// 验证 Vault 密码 —— 通过尝试解密测试向量验证密码是否正确
Future<bool> vaultVerifyPassword({
  required String password,
  required VaultEncryptedDataFfi encrypted,
}) => RustLib.instance.api.crateFrbApiVaultVerifyPassword(
  password: password,
  encrypted: encrypted,
);

/// 识别手写公式 —— 替代原 C ABI math_ink_recognize
///
/// 输入 JSON 序列化的笔触列表，返回 LaTeX 识别结果。
Future<MathRecognitionResultFfi> mathInkRecognize({
  required String strokesJson,
}) =>
    RustLib.instance.api.crateFrbApiMathInkRecognize(strokesJson: strokesJson);

/// 块数据
class BlockData {
  final String id;
  final String noteId;
  final String blockType;
  final String content;
  final int position;
  final String createdAt;
  final String updatedAt;

  const BlockData({
    required this.id,
    required this.noteId,
    required this.blockType,
    required this.content,
    required this.position,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      noteId.hashCode ^
      blockType.hashCode ^
      content.hashCode ^
      position.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BlockData &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          noteId == other.noteId &&
          blockType == other.blockType &&
          content == other.content &&
          position == other.position &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

/// 文件夹数据
class FolderData {
  final String id;
  final String name;
  final String? parentId;
  final int sortOrder;
  final String createdAt;
  final String updatedAt;

  const FolderData({
    required this.id,
    required this.name,
    this.parentId,
    required this.sortOrder,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      parentId.hashCode ^
      sortOrder.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FolderData &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          parentId == other.parentId &&
          sortOrder == other.sortOrder &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

/// 健康检查结果
class HealthCheckResult {
  final String status;
  final Map<String, bool> engines;

  /// 初始化失败的辅助引擎及错误信息，供 UI 提示"核心引擎未加载，功能受限"
  final List<String> warnings;

  const HealthCheckResult({
    required this.status,
    required this.engines,
    required this.warnings,
  });

  @override
  int get hashCode => status.hashCode ^ engines.hashCode ^ warnings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HealthCheckResult &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          engines == other.engines &&
          warnings == other.warnings;
}

/// 手写公式识别结果
class MathRecognitionResultFfi {
  final String latex;
  final double confidence;
  final List<String> alternatives;

  const MathRecognitionResultFfi({
    required this.latex,
    required this.confidence,
    required this.alternatives,
  });

  @override
  int get hashCode =>
      latex.hashCode ^ confidence.hashCode ^ alternatives.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MathRecognitionResultFfi &&
          runtimeType == other.runtimeType &&
          latex == other.latex &&
          confidence == other.confidence &&
          alternatives == other.alternatives;
}

/// CRDT 合并结果
class MergeResult {
  final BigInt appliedCount;
  final List<String> conflicts;

  const MergeResult({required this.appliedCount, required this.conflicts});

  @override
  int get hashCode => appliedCount.hashCode ^ conflicts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MergeResult &&
          runtimeType == other.runtimeType &&
          appliedCount == other.appliedCount &&
          conflicts == other.conflicts;
}

/// 笔记数据
class NoteData {
  final String id;
  final String title;
  final String content;
  final String folderId;
  final bool isPinned;
  final bool isEncrypted;
  final String createdAt;
  final String updatedAt;

  const NoteData({
    required this.id,
    required this.title,
    required this.content,
    required this.folderId,
    required this.isPinned,
    required this.isEncrypted,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      content.hashCode ^
      folderId.hashCode ^
      isPinned.hashCode ^
      isEncrypted.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NoteData &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          content == other.content &&
          folderId == other.folderId &&
          isPinned == other.isPinned &&
          isEncrypted == other.isEncrypted &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

/// OCR 识别结果（FFI 传输结构）—— FRB 自动生成对应 Dart 类
class OcrResultFfi {
  final String text;
  final List<String> lines;
  final double confidence;

  const OcrResultFfi({
    required this.text,
    required this.lines,
    required this.confidence,
  });

  @override
  int get hashCode => text.hashCode ^ lines.hashCode ^ confidence.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OcrResultFfi &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          lines == other.lines &&
          confidence == other.confidence;
}

/// 搜索结果
class SearchResult {
  final String noteId;
  final String title;
  final String snippet;
  final double score;

  const SearchResult({
    required this.noteId,
    required this.title,
    required this.snippet,
    required this.score,
  });

  @override
  int get hashCode =>
      noteId.hashCode ^ title.hashCode ^ snippet.hashCode ^ score.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchResult &&
          runtimeType == other.runtimeType &&
          noteId == other.noteId &&
          title == other.title &&
          snippet == other.snippet &&
          score == other.score;
}

/// 同步状态
class SyncStatusData {
  final String status;
  final String? lastSynced;
  final BigInt pendingChanges;

  const SyncStatusData({
    required this.status,
    this.lastSynced,
    required this.pendingChanges,
  });

  @override
  int get hashCode =>
      status.hashCode ^ lastSynced.hashCode ^ pendingChanges.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncStatusData &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          lastSynced == other.lastSynced &&
          pendingChanges == other.pendingChanges;
}

/// 标签数据
class TagData {
  final String id;
  final String name;
  final String createdAt;

  const TagData({
    required this.id,
    required this.name,
    required this.createdAt,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TagData &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          createdAt == other.createdAt;
}

/// 语音转文字结果
class TranscribeResultFfi {
  final String text;
  final BigInt durationMs;
  final List<TranscriptSegmentFfi> segments;

  const TranscribeResultFfi({
    required this.text,
    required this.durationMs,
    required this.segments,
  });

  @override
  int get hashCode => text.hashCode ^ durationMs.hashCode ^ segments.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TranscribeResultFfi &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          durationMs == other.durationMs &&
          segments == other.segments;
}

/// 转写片段（带时间戳）
class TranscriptSegmentFfi {
  final String text;
  final BigInt startMs;
  final BigInt endMs;

  const TranscriptSegmentFfi({
    required this.text,
    required this.startMs,
    required this.endMs,
  });

  @override
  int get hashCode => text.hashCode ^ startMs.hashCode ^ endMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TranscriptSegmentFfi &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          startMs == other.startMs &&
          endMs == other.endMs;
}

/// Vault 加密数据（FFI 传输结构）—— FRB 自动生成对应 Dart 类
class VaultEncryptedDataFfi {
  final String ciphertext;
  final String salt;
  final String nonce;
  final int memoryCost;
  final int timeCost;
  final int parallelism;

  const VaultEncryptedDataFfi({
    required this.ciphertext,
    required this.salt,
    required this.nonce,
    required this.memoryCost,
    required this.timeCost,
    required this.parallelism,
  });

  @override
  int get hashCode =>
      ciphertext.hashCode ^
      salt.hashCode ^
      nonce.hashCode ^
      memoryCost.hashCode ^
      timeCost.hashCode ^
      parallelism.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultEncryptedDataFfi &&
          runtimeType == other.runtimeType &&
          ciphertext == other.ciphertext &&
          salt == other.salt &&
          nonce == other.nonce &&
          memoryCost == other.memoryCost &&
          timeCost == other.timeCost &&
          parallelism == other.parallelism;
}

/// 版本信息 —— 替代原 FfiVersionInfo
class VersionInfo {
  final int apiVersion;
  final String rustVersion;
  final int compatibleMin;
  final List<String> features;

  const VersionInfo({
    required this.apiVersion,
    required this.rustVersion,
    required this.compatibleMin,
    required this.features,
  });

  @override
  int get hashCode =>
      apiVersion.hashCode ^
      rustVersion.hashCode ^
      compatibleMin.hashCode ^
      features.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VersionInfo &&
          runtimeType == other.runtimeType &&
          apiVersion == other.apiVersion &&
          rustVersion == other.rustVersion &&
          compatibleMin == other.compatibleMin &&
          features == other.features;
}
