// AUTO-GENERATED BY flutter_rust_bridge v2 — IO 平台实现 (mobile/desktop)
//
// 此文件由 `flutter_rust_bridge_codegen generate` 自动生成。
// 运行 codegen 后会被替换为真实的 IO 平台实现。

import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'frb_generated.dart';

/// IO 平台初始化实现 —— 加载 native 动态库并构造 RustLibApi
Future<void> initImpl(RustLib rustLib) async {
  final dylib = rustLib._loadNativeLibrary();
  rustLib.api = RustLibApi._(dylib);
}
