// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'frb_api.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -117999445;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'devnote_ffi',
        ioDirectory: 'rust-core/devnote-ffi/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateFrbApiCalculateCentrality();

  Future<void> crateFrbApiCanvasAddEdge({
    required String canvasId,
    required String edgeJson,
  });

  Future<void> crateFrbApiCanvasAddNode({
    required String canvasId,
    required String nodeJson,
  });

  Future<void> crateFrbApiCanvasAutoLayout({
    required String canvasId,
    required String layoutType,
  });

  Future<String> crateFrbApiCanvasLoadCanvas({required String path});

  Future<void> crateFrbApiCanvasRemoveNode({
    required String canvasId,
    required String nodeId,
  });

  Future<void> crateFrbApiCanvasSaveCanvas({
    required String canvasId,
    required String path,
  });

  Future<MergeResult> crateFrbApiCrdtMerge({
    required String docId,
    required String deviceId,
    required String remoteOpsJson,
  });

  Future<String> crateFrbApiCreateDatabase({required String name});

  Future<String> crateFrbApiCreateDeck({
    required String name,
    required String description,
  });

  Future<FolderData> crateFrbApiCreateFolder({
    required String name,
    String? parentId,
  });

  Future<NoteData> crateFrbApiCreateNote({
    required String title,
    required String content,
    required String folderId,
  });

  Future<TagData> crateFrbApiCreateTag({required String name});

  Future<String> crateFrbApiDatabaseAddView({
    required String dbId,
    required String name,
    required String viewType,
  });

  Future<String> crateFrbApiDatabaseQueryRows({required String dbId});

  Future<String> crateFrbApiDecrypt({
    required String ciphertextBase64,
    required String keyBase64,
  });

  Future<void> crateFrbApiDeleteBlock({required String id});

  Future<void> crateFrbApiDeleteFolder({required String id});

  Future<void> crateFrbApiDeleteNote({required String id});

  Future<void> crateFrbApiDeleteTag({required String id});

  Future<String> crateFrbApiDeriveKey({
    required String password,
    required String saltBase64,
  });

  Future<String> crateFrbApiDetectClusters();

  Future<String> crateFrbApiEncrypt({
    required String plaintextBase64,
    required String keyBase64,
  });

  Future<String> crateFrbApiEvaluateFormula({
    required String formula,
    required String rowValues,
    required String allRows,
  });

  Future<void> crateFrbApiExportMarkdown({
    required String notesJson,
    required String path,
  });

  Future<List<BlockData>> crateFrbApiGetBlocks({required String noteId});

  Future<String> crateFrbApiGetDueCards({
    required String deckId,
    BigInt? limit,
  });

  Future<FolderData?> crateFrbApiGetFolder({required String id});

  Future<NoteData?> crateFrbApiGetNote({required String id});

  Future<List<String>> crateFrbApiGetNoteIdsByTag({required String tagId});

  Future<SyncStatusData> crateFrbApiGetSyncStatus();

  Future<VersionInfo> crateFrbApiGetVersion();

  Future<HealthCheckResult> crateFrbApiHealthCheck();

  Future<String> crateFrbApiImportMarkdown({required String path});

  Future<void> crateFrbApiIndexOcrText({
    required String noteId,
    required String ocrText,
  });

  Future<void> crateFrbApiInitEngines({required String dbPath});

  Future<BlockData> crateFrbApiInsertBlock({
    required String noteId,
    required String blockType,
    required String content,
    BigInt? position,
  });

  Future<List<FolderData>> crateFrbApiListFolders({String? parentId});

  Future<List<NoteData>> crateFrbApiListNotes({required String folderId});

  Future<List<TagData>> crateFrbApiListTags();

  Future<MathRecognitionResultFfi> crateFrbApiMathInkRecognize({
    required String strokesJson,
  });

  Future<String> crateFrbApiOcrRecognizeImage({required String imageBase64});

  Future<OcrResultFfi> crateFrbApiOcrRecognizeImageDetailed({
    required String imageBase64,
  });

  Future<SyncStatusData> crateFrbApiPullChanges();

  Future<SyncStatusData> crateFrbApiPushChanges();

  Future<String> crateFrbApiReviewFlashcard({
    required String flashcardId,
    required int quality,
  });

  Future<List<SearchResult>> crateFrbApiSearchNotes({
    required String query,
    BigInt? limit,
    BigInt? offset,
  });

  Future<TranscribeResultFfi> crateFrbApiTranscribeAudio({
    required String audioBase64,
    required String lang,
  });

  Future<void> crateFrbApiUpdateBlock({
    required String id,
    required String content,
  });

  Future<FolderData> crateFrbApiUpdateFolder({
    required String id,
    required String name,
    String? parentId,
    int? sortOrder,
  });

  Future<NoteData> crateFrbApiUpdateNote({
    required String id,
    required String title,
    required String content,
  });

  Future<String> crateFrbApiVaultDecrypt({
    required String password,
    required VaultEncryptedDataFfi encrypted,
  });

  Future<VaultEncryptedDataFfi> crateFrbApiVaultEncrypt({
    required String password,
    required String plaintext,
  });

  Future<bool> crateFrbApiVaultVerifyPassword({
    required String password,
    required VaultEncryptedDataFfi encrypted,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateFrbApiCalculateCentrality() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateFrbApiCalculateCentralityConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiCalculateCentralityConstMeta =>
      const TaskConstMeta(debugName: 'calculate_centrality', argNames: []);

  @override
  Future<void> crateFrbApiCanvasAddEdge({
    required String canvasId,
    required String edgeJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(canvasId, serializer);
          sse_encode_String(edgeJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateFrbApiCanvasAddEdgeConstMeta,
        argValues: [canvasId, edgeJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiCanvasAddEdgeConstMeta => const TaskConstMeta(
    debugName: 'canvas_add_edge',
    argNames: ['canvasId', 'edgeJson'],
  );

  @override
  Future<void> crateFrbApiCanvasAddNode({
    required String canvasId,
    required String nodeJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(canvasId, serializer);
          sse_encode_String(nodeJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateFrbApiCanvasAddNodeConstMeta,
        argValues: [canvasId, nodeJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiCanvasAddNodeConstMeta => const TaskConstMeta(
    debugName: 'canvas_add_node',
    argNames: ['canvasId', 'nodeJson'],
  );

  @override
  Future<void> crateFrbApiCanvasAutoLayout({
    required String canvasId,
    required String layoutType,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(canvasId, serializer);
          sse_encode_String(layoutType, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateFrbApiCanvasAutoLayoutConstMeta,
        argValues: [canvasId, layoutType],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiCanvasAutoLayoutConstMeta =>
      const TaskConstMeta(
        debugName: 'canvas_auto_layout',
        argNames: ['canvasId', 'layoutType'],
      );

  @override
  Future<String> crateFrbApiCanvasLoadCanvas({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateFrbApiCanvasLoadCanvasConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiCanvasLoadCanvasConstMeta =>
      const TaskConstMeta(debugName: 'canvas_load_canvas', argNames: ['path']);

  @override
  Future<void> crateFrbApiCanvasRemoveNode({
    required String canvasId,
    required String nodeId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(canvasId, serializer);
          sse_encode_String(nodeId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateFrbApiCanvasRemoveNodeConstMeta,
        argValues: [canvasId, nodeId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiCanvasRemoveNodeConstMeta =>
      const TaskConstMeta(
        debugName: 'canvas_remove_node',
        argNames: ['canvasId', 'nodeId'],
      );

  @override
  Future<void> crateFrbApiCanvasSaveCanvas({
    required String canvasId,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(canvasId, serializer);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateFrbApiCanvasSaveCanvasConstMeta,
        argValues: [canvasId, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiCanvasSaveCanvasConstMeta =>
      const TaskConstMeta(
        debugName: 'canvas_save_canvas',
        argNames: ['canvasId', 'path'],
      );

  @override
  Future<MergeResult> crateFrbApiCrdtMerge({
    required String docId,
    required String deviceId,
    required String remoteOpsJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(docId, serializer);
          sse_encode_String(deviceId, serializer);
          sse_encode_String(remoteOpsJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_merge_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateFrbApiCrdtMergeConstMeta,
        argValues: [docId, deviceId, remoteOpsJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiCrdtMergeConstMeta => const TaskConstMeta(
    debugName: 'crdt_merge',
    argNames: ['docId', 'deviceId', 'remoteOpsJson'],
  );

  @override
  Future<String> crateFrbApiCreateDatabase({required String name}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateFrbApiCreateDatabaseConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiCreateDatabaseConstMeta =>
      const TaskConstMeta(debugName: 'create_database', argNames: ['name']);

  @override
  Future<String> crateFrbApiCreateDeck({
    required String name,
    required String description,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          sse_encode_String(description, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateFrbApiCreateDeckConstMeta,
        argValues: [name, description],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiCreateDeckConstMeta => const TaskConstMeta(
    debugName: 'create_deck',
    argNames: ['name', 'description'],
  );

  @override
  Future<FolderData> crateFrbApiCreateFolder({
    required String name,
    String? parentId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          sse_encode_opt_String(parentId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_folder_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateFrbApiCreateFolderConstMeta,
        argValues: [name, parentId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiCreateFolderConstMeta => const TaskConstMeta(
    debugName: 'create_folder',
    argNames: ['name', 'parentId'],
  );

  @override
  Future<NoteData> crateFrbApiCreateNote({
    required String title,
    required String content,
    required String folderId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(title, serializer);
          sse_encode_String(content, serializer);
          sse_encode_String(folderId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_note_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateFrbApiCreateNoteConstMeta,
        argValues: [title, content, folderId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiCreateNoteConstMeta => const TaskConstMeta(
    debugName: 'create_note',
    argNames: ['title', 'content', 'folderId'],
  );

  @override
  Future<TagData> crateFrbApiCreateTag({required String name}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_tag_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateFrbApiCreateTagConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiCreateTagConstMeta =>
      const TaskConstMeta(debugName: 'create_tag', argNames: ['name']);

  @override
  Future<String> crateFrbApiDatabaseAddView({
    required String dbId,
    required String name,
    required String viewType,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbId, serializer);
          sse_encode_String(name, serializer);
          sse_encode_String(viewType, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateFrbApiDatabaseAddViewConstMeta,
        argValues: [dbId, name, viewType],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiDatabaseAddViewConstMeta => const TaskConstMeta(
    debugName: 'database_add_view',
    argNames: ['dbId', 'name', 'viewType'],
  );

  @override
  Future<String> crateFrbApiDatabaseQueryRows({required String dbId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateFrbApiDatabaseQueryRowsConstMeta,
        argValues: [dbId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiDatabaseQueryRowsConstMeta =>
      const TaskConstMeta(debugName: 'database_query_rows', argNames: ['dbId']);

  @override
  Future<String> crateFrbApiDecrypt({
    required String ciphertextBase64,
    required String keyBase64,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(ciphertextBase64, serializer);
          sse_encode_String(keyBase64, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateFrbApiDecryptConstMeta,
        argValues: [ciphertextBase64, keyBase64],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiDecryptConstMeta => const TaskConstMeta(
    debugName: 'decrypt',
    argNames: ['ciphertextBase64', 'keyBase64'],
  );

  @override
  Future<void> crateFrbApiDeleteBlock({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateFrbApiDeleteBlockConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiDeleteBlockConstMeta =>
      const TaskConstMeta(debugName: 'delete_block', argNames: ['id']);

  @override
  Future<void> crateFrbApiDeleteFolder({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateFrbApiDeleteFolderConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiDeleteFolderConstMeta =>
      const TaskConstMeta(debugName: 'delete_folder', argNames: ['id']);

  @override
  Future<void> crateFrbApiDeleteNote({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateFrbApiDeleteNoteConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiDeleteNoteConstMeta =>
      const TaskConstMeta(debugName: 'delete_note', argNames: ['id']);

  @override
  Future<void> crateFrbApiDeleteTag({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateFrbApiDeleteTagConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiDeleteTagConstMeta =>
      const TaskConstMeta(debugName: 'delete_tag', argNames: ['id']);

  @override
  Future<String> crateFrbApiDeriveKey({
    required String password,
    required String saltBase64,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(password, serializer);
          sse_encode_String(saltBase64, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateFrbApiDeriveKeyConstMeta,
        argValues: [password, saltBase64],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiDeriveKeyConstMeta => const TaskConstMeta(
    debugName: 'derive_key',
    argNames: ['password', 'saltBase64'],
  );

  @override
  Future<String> crateFrbApiDetectClusters() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateFrbApiDetectClustersConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiDetectClustersConstMeta =>
      const TaskConstMeta(debugName: 'detect_clusters', argNames: []);

  @override
  Future<String> crateFrbApiEncrypt({
    required String plaintextBase64,
    required String keyBase64,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(plaintextBase64, serializer);
          sse_encode_String(keyBase64, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateFrbApiEncryptConstMeta,
        argValues: [plaintextBase64, keyBase64],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiEncryptConstMeta => const TaskConstMeta(
    debugName: 'encrypt',
    argNames: ['plaintextBase64', 'keyBase64'],
  );

  @override
  Future<String> crateFrbApiEvaluateFormula({
    required String formula,
    required String rowValues,
    required String allRows,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(formula, serializer);
          sse_encode_String(rowValues, serializer);
          sse_encode_String(allRows, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateFrbApiEvaluateFormulaConstMeta,
        argValues: [formula, rowValues, allRows],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiEvaluateFormulaConstMeta => const TaskConstMeta(
    debugName: 'evaluate_formula',
    argNames: ['formula', 'rowValues', 'allRows'],
  );

  @override
  Future<void> crateFrbApiExportMarkdown({
    required String notesJson,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(notesJson, serializer);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateFrbApiExportMarkdownConstMeta,
        argValues: [notesJson, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiExportMarkdownConstMeta => const TaskConstMeta(
    debugName: 'export_markdown',
    argNames: ['notesJson', 'path'],
  );

  @override
  Future<List<BlockData>> crateFrbApiGetBlocks({required String noteId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(noteId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_block_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateFrbApiGetBlocksConstMeta,
        argValues: [noteId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiGetBlocksConstMeta =>
      const TaskConstMeta(debugName: 'get_blocks', argNames: ['noteId']);

  @override
  Future<String> crateFrbApiGetDueCards({
    required String deckId,
    BigInt? limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(deckId, serializer);
          sse_encode_opt_box_autoadd_usize(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateFrbApiGetDueCardsConstMeta,
        argValues: [deckId, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiGetDueCardsConstMeta => const TaskConstMeta(
    debugName: 'get_due_cards',
    argNames: ['deckId', 'limit'],
  );

  @override
  Future<FolderData?> crateFrbApiGetFolder({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_folder_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateFrbApiGetFolderConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiGetFolderConstMeta =>
      const TaskConstMeta(debugName: 'get_folder', argNames: ['id']);

  @override
  Future<NoteData?> crateFrbApiGetNote({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_note_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateFrbApiGetNoteConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiGetNoteConstMeta =>
      const TaskConstMeta(debugName: 'get_note', argNames: ['id']);

  @override
  Future<List<String>> crateFrbApiGetNoteIdsByTag({required String tagId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(tagId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateFrbApiGetNoteIdsByTagConstMeta,
        argValues: [tagId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiGetNoteIdsByTagConstMeta => const TaskConstMeta(
    debugName: 'get_note_ids_by_tag',
    argNames: ['tagId'],
  );

  @override
  Future<SyncStatusData> crateFrbApiGetSyncStatus() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_sync_status_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateFrbApiGetSyncStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiGetSyncStatusConstMeta =>
      const TaskConstMeta(debugName: 'get_sync_status', argNames: []);

  @override
  Future<VersionInfo> crateFrbApiGetVersion() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 32,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_version_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateFrbApiGetVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiGetVersionConstMeta =>
      const TaskConstMeta(debugName: 'get_version', argNames: []);

  @override
  Future<HealthCheckResult> crateFrbApiHealthCheck() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 33,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_health_check_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateFrbApiHealthCheckConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiHealthCheckConstMeta =>
      const TaskConstMeta(debugName: 'health_check', argNames: []);

  @override
  Future<String> crateFrbApiImportMarkdown({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 34,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateFrbApiImportMarkdownConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiImportMarkdownConstMeta =>
      const TaskConstMeta(debugName: 'import_markdown', argNames: ['path']);

  @override
  Future<void> crateFrbApiIndexOcrText({
    required String noteId,
    required String ocrText,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(noteId, serializer);
          sse_encode_String(ocrText, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 35,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateFrbApiIndexOcrTextConstMeta,
        argValues: [noteId, ocrText],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiIndexOcrTextConstMeta => const TaskConstMeta(
    debugName: 'index_ocr_text',
    argNames: ['noteId', 'ocrText'],
  );

  @override
  Future<void> crateFrbApiInitEngines({required String dbPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 36,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateFrbApiInitEnginesConstMeta,
        argValues: [dbPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiInitEnginesConstMeta =>
      const TaskConstMeta(debugName: 'init_engines', argNames: ['dbPath']);

  @override
  Future<BlockData> crateFrbApiInsertBlock({
    required String noteId,
    required String blockType,
    required String content,
    BigInt? position,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(noteId, serializer);
          sse_encode_String(blockType, serializer);
          sse_encode_String(content, serializer);
          sse_encode_opt_box_autoadd_usize(position, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 37,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_block_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateFrbApiInsertBlockConstMeta,
        argValues: [noteId, blockType, content, position],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiInsertBlockConstMeta => const TaskConstMeta(
    debugName: 'insert_block',
    argNames: ['noteId', 'blockType', 'content', 'position'],
  );

  @override
  Future<List<FolderData>> crateFrbApiListFolders({String? parentId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(parentId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 38,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_folder_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateFrbApiListFoldersConstMeta,
        argValues: [parentId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiListFoldersConstMeta =>
      const TaskConstMeta(debugName: 'list_folders', argNames: ['parentId']);

  @override
  Future<List<NoteData>> crateFrbApiListNotes({required String folderId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(folderId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 39,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_note_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateFrbApiListNotesConstMeta,
        argValues: [folderId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiListNotesConstMeta =>
      const TaskConstMeta(debugName: 'list_notes', argNames: ['folderId']);

  @override
  Future<List<TagData>> crateFrbApiListTags() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 40,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_tag_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateFrbApiListTagsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiListTagsConstMeta =>
      const TaskConstMeta(debugName: 'list_tags', argNames: []);

  @override
  Future<MathRecognitionResultFfi> crateFrbApiMathInkRecognize({
    required String strokesJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(strokesJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 41,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_math_recognition_result_ffi,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateFrbApiMathInkRecognizeConstMeta,
        argValues: [strokesJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiMathInkRecognizeConstMeta =>
      const TaskConstMeta(
        debugName: 'math_ink_recognize',
        argNames: ['strokesJson'],
      );

  @override
  Future<String> crateFrbApiOcrRecognizeImage({required String imageBase64}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(imageBase64, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 42,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateFrbApiOcrRecognizeImageConstMeta,
        argValues: [imageBase64],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiOcrRecognizeImageConstMeta =>
      const TaskConstMeta(
        debugName: 'ocr_recognize_image',
        argNames: ['imageBase64'],
      );

  @override
  Future<OcrResultFfi> crateFrbApiOcrRecognizeImageDetailed({
    required String imageBase64,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(imageBase64, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 43,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ocr_result_ffi,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateFrbApiOcrRecognizeImageDetailedConstMeta,
        argValues: [imageBase64],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiOcrRecognizeImageDetailedConstMeta =>
      const TaskConstMeta(
        debugName: 'ocr_recognize_image_detailed',
        argNames: ['imageBase64'],
      );

  @override
  Future<SyncStatusData> crateFrbApiPullChanges() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 44,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_sync_status_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateFrbApiPullChangesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiPullChangesConstMeta =>
      const TaskConstMeta(debugName: 'pull_changes', argNames: []);

  @override
  Future<SyncStatusData> crateFrbApiPushChanges() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 45,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_sync_status_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateFrbApiPushChangesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiPushChangesConstMeta =>
      const TaskConstMeta(debugName: 'push_changes', argNames: []);

  @override
  Future<String> crateFrbApiReviewFlashcard({
    required String flashcardId,
    required int quality,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(flashcardId, serializer);
          sse_encode_u_8(quality, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 46,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateFrbApiReviewFlashcardConstMeta,
        argValues: [flashcardId, quality],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiReviewFlashcardConstMeta => const TaskConstMeta(
    debugName: 'review_flashcard',
    argNames: ['flashcardId', 'quality'],
  );

  @override
  Future<List<SearchResult>> crateFrbApiSearchNotes({
    required String query,
    BigInt? limit,
    BigInt? offset,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(query, serializer);
          sse_encode_opt_box_autoadd_usize(limit, serializer);
          sse_encode_opt_box_autoadd_usize(offset, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 47,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_search_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateFrbApiSearchNotesConstMeta,
        argValues: [query, limit, offset],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiSearchNotesConstMeta => const TaskConstMeta(
    debugName: 'search_notes',
    argNames: ['query', 'limit', 'offset'],
  );

  @override
  Future<TranscribeResultFfi> crateFrbApiTranscribeAudio({
    required String audioBase64,
    required String lang,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(audioBase64, serializer);
          sse_encode_String(lang, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 48,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_transcribe_result_ffi,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateFrbApiTranscribeAudioConstMeta,
        argValues: [audioBase64, lang],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiTranscribeAudioConstMeta => const TaskConstMeta(
    debugName: 'transcribe_audio',
    argNames: ['audioBase64', 'lang'],
  );

  @override
  Future<void> crateFrbApiUpdateBlock({
    required String id,
    required String content,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          sse_encode_String(content, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 49,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateFrbApiUpdateBlockConstMeta,
        argValues: [id, content],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiUpdateBlockConstMeta => const TaskConstMeta(
    debugName: 'update_block',
    argNames: ['id', 'content'],
  );

  @override
  Future<FolderData> crateFrbApiUpdateFolder({
    required String id,
    required String name,
    String? parentId,
    int? sortOrder,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          sse_encode_String(name, serializer);
          sse_encode_opt_String(parentId, serializer);
          sse_encode_opt_box_autoadd_i_32(sortOrder, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 50,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_folder_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateFrbApiUpdateFolderConstMeta,
        argValues: [id, name, parentId, sortOrder],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiUpdateFolderConstMeta => const TaskConstMeta(
    debugName: 'update_folder',
    argNames: ['id', 'name', 'parentId', 'sortOrder'],
  );

  @override
  Future<NoteData> crateFrbApiUpdateNote({
    required String id,
    required String title,
    required String content,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          sse_encode_String(title, serializer);
          sse_encode_String(content, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 51,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_note_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateFrbApiUpdateNoteConstMeta,
        argValues: [id, title, content],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiUpdateNoteConstMeta => const TaskConstMeta(
    debugName: 'update_note',
    argNames: ['id', 'title', 'content'],
  );

  @override
  Future<String> crateFrbApiVaultDecrypt({
    required String password,
    required VaultEncryptedDataFfi encrypted,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(password, serializer);
          sse_encode_box_autoadd_vault_encrypted_data_ffi(
            encrypted,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 52,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateFrbApiVaultDecryptConstMeta,
        argValues: [password, encrypted],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiVaultDecryptConstMeta => const TaskConstMeta(
    debugName: 'vault_decrypt',
    argNames: ['password', 'encrypted'],
  );

  @override
  Future<VaultEncryptedDataFfi> crateFrbApiVaultEncrypt({
    required String password,
    required String plaintext,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(password, serializer);
          sse_encode_String(plaintext, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 53,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_vault_encrypted_data_ffi,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateFrbApiVaultEncryptConstMeta,
        argValues: [password, plaintext],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiVaultEncryptConstMeta => const TaskConstMeta(
    debugName: 'vault_encrypt',
    argNames: ['password', 'plaintext'],
  );

  @override
  Future<bool> crateFrbApiVaultVerifyPassword({
    required String password,
    required VaultEncryptedDataFfi encrypted,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(password, serializer);
          sse_encode_box_autoadd_vault_encrypted_data_ffi(
            encrypted,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 54,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateFrbApiVaultVerifyPasswordConstMeta,
        argValues: [password, encrypted],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiVaultVerifyPasswordConstMeta =>
      const TaskConstMeta(
        debugName: 'vault_verify_password',
        argNames: ['password', 'encrypted'],
      );

  @protected
  Map<String, bool> dco_decode_Map_String_bool_None(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Map.fromEntries(
      dco_decode_list_record_string_bool(raw).map((e) => MapEntry(e.$1, e.$2)),
    );
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  BlockData dco_decode_block_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return BlockData(
      id: dco_decode_String(arr[0]),
      noteId: dco_decode_String(arr[1]),
      blockType: dco_decode_String(arr[2]),
      content: dco_decode_String(arr[3]),
      position: dco_decode_i_32(arr[4]),
      createdAt: dco_decode_String(arr[5]),
      updatedAt: dco_decode_String(arr[6]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  FolderData dco_decode_box_autoadd_folder_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_folder_data(raw);
  }

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  NoteData dco_decode_box_autoadd_note_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_note_data(raw);
  }

  @protected
  BigInt dco_decode_box_autoadd_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_usize(raw);
  }

  @protected
  VaultEncryptedDataFfi dco_decode_box_autoadd_vault_encrypted_data_ffi(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_vault_encrypted_data_ffi(raw);
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FolderData dco_decode_folder_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return FolderData(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      parentId: dco_decode_opt_String(arr[2]),
      sortOrder: dco_decode_i_32(arr[3]),
      createdAt: dco_decode_String(arr[4]),
      updatedAt: dco_decode_String(arr[5]),
    );
  }

  @protected
  HealthCheckResult dco_decode_health_check_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return HealthCheckResult(
      status: dco_decode_String(arr[0]),
      engines: dco_decode_Map_String_bool_None(arr[1]),
      warnings: dco_decode_list_String(arr[2]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<BlockData> dco_decode_list_block_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_block_data).toList();
  }

  @protected
  List<FolderData> dco_decode_list_folder_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_folder_data).toList();
  }

  @protected
  List<NoteData> dco_decode_list_note_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_note_data).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(String, bool)> dco_decode_list_record_string_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_record_string_bool).toList();
  }

  @protected
  List<SearchResult> dco_decode_list_search_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_search_result).toList();
  }

  @protected
  List<TagData> dco_decode_list_tag_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_tag_data).toList();
  }

  @protected
  List<TranscriptSegmentFfi> dco_decode_list_transcript_segment_ffi(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_transcript_segment_ffi)
        .toList();
  }

  @protected
  MathRecognitionResultFfi dco_decode_math_recognition_result_ffi(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return MathRecognitionResultFfi(
      latex: dco_decode_String(arr[0]),
      confidence: dco_decode_f_32(arr[1]),
      alternatives: dco_decode_list_String(arr[2]),
    );
  }

  @protected
  MergeResult dco_decode_merge_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return MergeResult(
      appliedCount: dco_decode_usize(arr[0]),
      conflicts: dco_decode_list_String(arr[1]),
    );
  }

  @protected
  NoteData dco_decode_note_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return NoteData(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      content: dco_decode_String(arr[2]),
      folderId: dco_decode_String(arr[3]),
      isPinned: dco_decode_bool(arr[4]),
      isEncrypted: dco_decode_bool(arr[5]),
      createdAt: dco_decode_String(arr[6]),
      updatedAt: dco_decode_String(arr[7]),
    );
  }

  @protected
  OcrResultFfi dco_decode_ocr_result_ffi(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return OcrResultFfi(
      text: dco_decode_String(arr[0]),
      lines: dco_decode_list_String(arr[1]),
      confidence: dco_decode_f_32(arr[2]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  FolderData? dco_decode_opt_box_autoadd_folder_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_folder_data(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_32(raw);
  }

  @protected
  NoteData? dco_decode_opt_box_autoadd_note_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_note_data(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_usize(raw);
  }

  @protected
  (String, bool) dco_decode_record_string_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_String(arr[0]), dco_decode_bool(arr[1]));
  }

  @protected
  SearchResult dco_decode_search_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SearchResult(
      noteId: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      snippet: dco_decode_String(arr[2]),
      score: dco_decode_f_64(arr[3]),
    );
  }

  @protected
  SyncStatusData dco_decode_sync_status_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SyncStatusData(
      status: dco_decode_String(arr[0]),
      lastSynced: dco_decode_opt_String(arr[1]),
      pendingChanges: dco_decode_u_64(arr[2]),
    );
  }

  @protected
  TagData dco_decode_tag_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return TagData(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      createdAt: dco_decode_String(arr[2]),
    );
  }

  @protected
  TranscribeResultFfi dco_decode_transcribe_result_ffi(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return TranscribeResultFfi(
      text: dco_decode_String(arr[0]),
      durationMs: dco_decode_u_64(arr[1]),
      segments: dco_decode_list_transcript_segment_ffi(arr[2]),
    );
  }

  @protected
  TranscriptSegmentFfi dco_decode_transcript_segment_ffi(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return TranscriptSegmentFfi(
      text: dco_decode_String(arr[0]),
      startMs: dco_decode_u_64(arr[1]),
      endMs: dco_decode_u_64(arr[2]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  VaultEncryptedDataFfi dco_decode_vault_encrypted_data_ffi(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return VaultEncryptedDataFfi(
      ciphertext: dco_decode_String(arr[0]),
      salt: dco_decode_String(arr[1]),
      nonce: dco_decode_String(arr[2]),
      memoryCost: dco_decode_u_32(arr[3]),
      timeCost: dco_decode_u_32(arr[4]),
      parallelism: dco_decode_u_32(arr[5]),
    );
  }

  @protected
  VersionInfo dco_decode_version_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return VersionInfo(
      apiVersion: dco_decode_u_32(arr[0]),
      rustVersion: dco_decode_String(arr[1]),
      compatibleMin: dco_decode_u_32(arr[2]),
      features: dco_decode_list_String(arr[3]),
    );
  }

  @protected
  Map<String, bool> sse_decode_Map_String_bool_None(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_record_string_bool(deserializer);
    return Map.fromEntries(inner.map((e) => MapEntry(e.$1, e.$2)));
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  BlockData sse_decode_block_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_noteId = sse_decode_String(deserializer);
    var var_blockType = sse_decode_String(deserializer);
    var var_content = sse_decode_String(deserializer);
    var var_position = sse_decode_i_32(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    var var_updatedAt = sse_decode_String(deserializer);
    return BlockData(
      id: var_id,
      noteId: var_noteId,
      blockType: var_blockType,
      content: var_content,
      position: var_position,
      createdAt: var_createdAt,
      updatedAt: var_updatedAt,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  FolderData sse_decode_box_autoadd_folder_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_folder_data(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_32(deserializer));
  }

  @protected
  NoteData sse_decode_box_autoadd_note_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_note_data(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_usize(deserializer));
  }

  @protected
  VaultEncryptedDataFfi sse_decode_box_autoadd_vault_encrypted_data_ffi(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_vault_encrypted_data_ffi(deserializer));
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  FolderData sse_decode_folder_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_parentId = sse_decode_opt_String(deserializer);
    var var_sortOrder = sse_decode_i_32(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    var var_updatedAt = sse_decode_String(deserializer);
    return FolderData(
      id: var_id,
      name: var_name,
      parentId: var_parentId,
      sortOrder: var_sortOrder,
      createdAt: var_createdAt,
      updatedAt: var_updatedAt,
    );
  }

  @protected
  HealthCheckResult sse_decode_health_check_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_status = sse_decode_String(deserializer);
    var var_engines = sse_decode_Map_String_bool_None(deserializer);
    var var_warnings = sse_decode_list_String(deserializer);
    return HealthCheckResult(
      status: var_status,
      engines: var_engines,
      warnings: var_warnings,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<BlockData> sse_decode_list_block_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BlockData>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_block_data(deserializer));
    }
    return ans_;
  }

  @protected
  List<FolderData> sse_decode_list_folder_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FolderData>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_folder_data(deserializer));
    }
    return ans_;
  }

  @protected
  List<NoteData> sse_decode_list_note_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <NoteData>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_note_data(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(String, bool)> sse_decode_list_record_string_bool(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, bool)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_bool(deserializer));
    }
    return ans_;
  }

  @protected
  List<SearchResult> sse_decode_list_search_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SearchResult>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_search_result(deserializer));
    }
    return ans_;
  }

  @protected
  List<TagData> sse_decode_list_tag_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TagData>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_tag_data(deserializer));
    }
    return ans_;
  }

  @protected
  List<TranscriptSegmentFfi> sse_decode_list_transcript_segment_ffi(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TranscriptSegmentFfi>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_transcript_segment_ffi(deserializer));
    }
    return ans_;
  }

  @protected
  MathRecognitionResultFfi sse_decode_math_recognition_result_ffi(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_latex = sse_decode_String(deserializer);
    var var_confidence = sse_decode_f_32(deserializer);
    var var_alternatives = sse_decode_list_String(deserializer);
    return MathRecognitionResultFfi(
      latex: var_latex,
      confidence: var_confidence,
      alternatives: var_alternatives,
    );
  }

  @protected
  MergeResult sse_decode_merge_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_appliedCount = sse_decode_usize(deserializer);
    var var_conflicts = sse_decode_list_String(deserializer);
    return MergeResult(
      appliedCount: var_appliedCount,
      conflicts: var_conflicts,
    );
  }

  @protected
  NoteData sse_decode_note_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_content = sse_decode_String(deserializer);
    var var_folderId = sse_decode_String(deserializer);
    var var_isPinned = sse_decode_bool(deserializer);
    var var_isEncrypted = sse_decode_bool(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    var var_updatedAt = sse_decode_String(deserializer);
    return NoteData(
      id: var_id,
      title: var_title,
      content: var_content,
      folderId: var_folderId,
      isPinned: var_isPinned,
      isEncrypted: var_isEncrypted,
      createdAt: var_createdAt,
      updatedAt: var_updatedAt,
    );
  }

  @protected
  OcrResultFfi sse_decode_ocr_result_ffi(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_text = sse_decode_String(deserializer);
    var var_lines = sse_decode_list_String(deserializer);
    var var_confidence = sse_decode_f_32(deserializer);
    return OcrResultFfi(
      text: var_text,
      lines: var_lines,
      confidence: var_confidence,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  FolderData? sse_decode_opt_box_autoadd_folder_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_folder_data(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  NoteData? sse_decode_opt_box_autoadd_note_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_note_data(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_usize(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (String, bool) sse_decode_record_string_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_bool(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  SearchResult sse_decode_search_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_noteId = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_snippet = sse_decode_String(deserializer);
    var var_score = sse_decode_f_64(deserializer);
    return SearchResult(
      noteId: var_noteId,
      title: var_title,
      snippet: var_snippet,
      score: var_score,
    );
  }

  @protected
  SyncStatusData sse_decode_sync_status_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_status = sse_decode_String(deserializer);
    var var_lastSynced = sse_decode_opt_String(deserializer);
    var var_pendingChanges = sse_decode_u_64(deserializer);
    return SyncStatusData(
      status: var_status,
      lastSynced: var_lastSynced,
      pendingChanges: var_pendingChanges,
    );
  }

  @protected
  TagData sse_decode_tag_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    return TagData(id: var_id, name: var_name, createdAt: var_createdAt);
  }

  @protected
  TranscribeResultFfi sse_decode_transcribe_result_ffi(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_text = sse_decode_String(deserializer);
    var var_durationMs = sse_decode_u_64(deserializer);
    var var_segments = sse_decode_list_transcript_segment_ffi(deserializer);
    return TranscribeResultFfi(
      text: var_text,
      durationMs: var_durationMs,
      segments: var_segments,
    );
  }

  @protected
  TranscriptSegmentFfi sse_decode_transcript_segment_ffi(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_text = sse_decode_String(deserializer);
    var var_startMs = sse_decode_u_64(deserializer);
    var var_endMs = sse_decode_u_64(deserializer);
    return TranscriptSegmentFfi(
      text: var_text,
      startMs: var_startMs,
      endMs: var_endMs,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  VaultEncryptedDataFfi sse_decode_vault_encrypted_data_ffi(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ciphertext = sse_decode_String(deserializer);
    var var_salt = sse_decode_String(deserializer);
    var var_nonce = sse_decode_String(deserializer);
    var var_memoryCost = sse_decode_u_32(deserializer);
    var var_timeCost = sse_decode_u_32(deserializer);
    var var_parallelism = sse_decode_u_32(deserializer);
    return VaultEncryptedDataFfi(
      ciphertext: var_ciphertext,
      salt: var_salt,
      nonce: var_nonce,
      memoryCost: var_memoryCost,
      timeCost: var_timeCost,
      parallelism: var_parallelism,
    );
  }

  @protected
  VersionInfo sse_decode_version_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_apiVersion = sse_decode_u_32(deserializer);
    var var_rustVersion = sse_decode_String(deserializer);
    var var_compatibleMin = sse_decode_u_32(deserializer);
    var var_features = sse_decode_list_String(deserializer);
    return VersionInfo(
      apiVersion: var_apiVersion,
      rustVersion: var_rustVersion,
      compatibleMin: var_compatibleMin,
      features: var_features,
    );
  }

  @protected
  void sse_encode_Map_String_bool_None(
    Map<String, bool> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_record_string_bool(
      self.entries.map((e) => (e.key, e.value)).toList(),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_block_data(BlockData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.noteId, serializer);
    sse_encode_String(self.blockType, serializer);
    sse_encode_String(self.content, serializer);
    sse_encode_i_32(self.position, serializer);
    sse_encode_String(self.createdAt, serializer);
    sse_encode_String(self.updatedAt, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_folder_data(
    FolderData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_folder_data(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_note_data(
    NoteData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_note_data(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_vault_encrypted_data_ffi(
    VaultEncryptedDataFfi self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_vault_encrypted_data_ffi(self, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_folder_data(FolderData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_opt_String(self.parentId, serializer);
    sse_encode_i_32(self.sortOrder, serializer);
    sse_encode_String(self.createdAt, serializer);
    sse_encode_String(self.updatedAt, serializer);
  }

  @protected
  void sse_encode_health_check_result(
    HealthCheckResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.status, serializer);
    sse_encode_Map_String_bool_None(self.engines, serializer);
    sse_encode_list_String(self.warnings, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_block_data(
    List<BlockData> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_block_data(item, serializer);
    }
  }

  @protected
  void sse_encode_list_folder_data(
    List<FolderData> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_folder_data(item, serializer);
    }
  }

  @protected
  void sse_encode_list_note_data(
    List<NoteData> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_note_data(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_record_string_bool(
    List<(String, bool)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_bool(item, serializer);
    }
  }

  @protected
  void sse_encode_list_search_result(
    List<SearchResult> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_search_result(item, serializer);
    }
  }

  @protected
  void sse_encode_list_tag_data(List<TagData> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_tag_data(item, serializer);
    }
  }

  @protected
  void sse_encode_list_transcript_segment_ffi(
    List<TranscriptSegmentFfi> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_transcript_segment_ffi(item, serializer);
    }
  }

  @protected
  void sse_encode_math_recognition_result_ffi(
    MathRecognitionResultFfi self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.latex, serializer);
    sse_encode_f_32(self.confidence, serializer);
    sse_encode_list_String(self.alternatives, serializer);
  }

  @protected
  void sse_encode_merge_result(MergeResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(self.appliedCount, serializer);
    sse_encode_list_String(self.conflicts, serializer);
  }

  @protected
  void sse_encode_note_data(NoteData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.content, serializer);
    sse_encode_String(self.folderId, serializer);
    sse_encode_bool(self.isPinned, serializer);
    sse_encode_bool(self.isEncrypted, serializer);
    sse_encode_String(self.createdAt, serializer);
    sse_encode_String(self.updatedAt, serializer);
  }

  @protected
  void sse_encode_ocr_result_ffi(OcrResultFfi self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.text, serializer);
    sse_encode_list_String(self.lines, serializer);
    sse_encode_f_32(self.confidence, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_folder_data(
    FolderData? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_folder_data(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_note_data(
    NoteData? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_note_data(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_usize(
    BigInt? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_usize(self, serializer);
    }
  }

  @protected
  void sse_encode_record_string_bool(
    (String, bool) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_bool(self.$2, serializer);
  }

  @protected
  void sse_encode_search_result(SearchResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.noteId, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.snippet, serializer);
    sse_encode_f_64(self.score, serializer);
  }

  @protected
  void sse_encode_sync_status_data(
    SyncStatusData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.status, serializer);
    sse_encode_opt_String(self.lastSynced, serializer);
    sse_encode_u_64(self.pendingChanges, serializer);
  }

  @protected
  void sse_encode_tag_data(TagData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.createdAt, serializer);
  }

  @protected
  void sse_encode_transcribe_result_ffi(
    TranscribeResultFfi self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.text, serializer);
    sse_encode_u_64(self.durationMs, serializer);
    sse_encode_list_transcript_segment_ffi(self.segments, serializer);
  }

  @protected
  void sse_encode_transcript_segment_ffi(
    TranscriptSegmentFfi self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.text, serializer);
    sse_encode_u_64(self.startMs, serializer);
    sse_encode_u_64(self.endMs, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_vault_encrypted_data_ffi(
    VaultEncryptedDataFfi self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.ciphertext, serializer);
    sse_encode_String(self.salt, serializer);
    sse_encode_String(self.nonce, serializer);
    sse_encode_u_32(self.memoryCost, serializer);
    sse_encode_u_32(self.timeCost, serializer);
    sse_encode_u_32(self.parallelism, serializer);
  }

  @protected
  void sse_encode_version_info(VersionInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.apiVersion, serializer);
    sse_encode_String(self.rustVersion, serializer);
    sse_encode_u_32(self.compatibleMin, serializer);
    sse_encode_list_String(self.features, serializer);
  }
}
