// AUTO-GENERATED BY flutter_rust_bridge v2 — Dart API 绑定
//
// 此文件由 `flutter_rust_bridge_codegen generate` 自动生成。
// 首次使用前必须运行：
//   flutter_rust_bridge_codegen generate
//
// 每个函数对应 rust-core/devnote-ffi/src/frb_api.rs 中的 pub fn。
// FRB 使用 SSE 编解码器（比 JSON 快数倍），类型安全，自动内存管理。
//
// 文档: https://cjycode.com/flutter_rust_bridge/

export 'frb_generated.dart';
export 'frb_api.dart';
