// AUTO-GENERATED BY flutter_rust_bridge v2 — Dart API 绑定
//
// 此文件由 `flutter_rust_bridge_codegen generate` 自动生成。
// 首次使用前必须运行：
//   flutter_rust_bridge_codegen generate
//
// 每个函数对应 rust-core/devnote-ffi/src/frb_api.rs 中的 pub fn。
// FRB 使用 SSE 编解码器（比 JSON 快数倍），类型安全，自动内存管理。
//
// 文档: https://cjycode.com/flutter_rust_bridge/

import 'frb_generated.dart';

// ============================================================
// FRB 数据类型 —— 对应 frb_api.rs 中的 #[derive(Serialize)] 结构体
// FRB codegen 自动生成 Dart 类，无需手写序列化代码
// ============================================================

/// 版本信息 —— 对应 Rust VersionInfo
class VersionInfo {
  final int apiVersion;
  final String rustVersion;
  final int compatibleMin;
  final List<String> features;

  VersionInfo({
    required this.apiVersion,
    required this.rustVersion,
    required this.compatibleMin,
    required this.features,
  });
}

/// 健康检查结果 —— 对应 Rust HealthCheckResult
class HealthCheckResult {
  final String status;
  final Map<String, bool> engines;

  HealthCheckResult({required this.status, required this.engines});
}

/// 笔记数据 —— 对应 Rust NoteData
class NoteData {
  final String id;
  final String title;
  final String content;
  final String folderId;
  final bool isPinned;
  final bool isEncrypted;
  final String createdAt;
  final String updatedAt;

  NoteData({
    required this.id,
    required this.title,
    required this.content,
    required this.folderId,
    required this.isPinned,
    required this.isEncrypted,
    required this.createdAt,
    required this.updatedAt,
  });

  Map<String, dynamic> toJson() => {
        'id': id,
        'title': title,
        'content': content,
        'folder_id': folderId,
        'is_pinned': isPinned,
        'is_encrypted': isEncrypted,
        'created_at': createdAt,
        'updated_at': updatedAt,
      };
}

/// 文件夹数据 —— 对应 Rust FolderData
class FolderData {
  final String id;
  final String name;
  final String? parentId;
  final int sortOrder;
  final String createdAt;
  final String updatedAt;

  FolderData({
    required this.id,
    required this.name,
    this.parentId,
    required this.sortOrder,
    required this.createdAt,
    required this.updatedAt,
  });

  Map<String, dynamic> toJson() => {
        'id': id,
        'name': name,
        'parent_id': parentId,
        'sort_order': sortOrder,
        'created_at': createdAt,
        'updated_at': updatedAt,
      };
}

/// 标签数据 —— 对应 Rust TagData
class TagData {
  final String id;
  final String name;
  final String createdAt;

  TagData({required this.id, required this.name, required this.createdAt});

  Map<String, dynamic> toJson() =>
      {'id': id, 'name': name, 'created_at': createdAt};
}

/// 块数据 —— 对应 Rust BlockData
class BlockData {
  final String id;
  final String noteId;
  final String blockType;
  final String content;
  final int position;
  final String createdAt;
  final String updatedAt;

  BlockData({
    required this.id,
    required this.noteId,
    required this.blockType,
    required this.content,
    required this.position,
    required this.createdAt,
    required this.updatedAt,
  });

  Map<String, dynamic> toJson() => {
        'id': id,
        'note_id': noteId,
        'block_type': blockType,
        'content': content,
        'position': position,
        'created_at': createdAt,
        'updated_at': updatedAt,
      };
}

/// 搜索结果 —— 对应 Rust SearchResult
class SearchResult {
  final String noteId;
  final String title;
  final String snippet;
  final double score;

  SearchResult({
    required this.noteId,
    required this.title,
    required this.snippet,
    required this.score,
  });

  Map<String, dynamic> toJson() => {
        'note_id': noteId,
        'title': title,
        'snippet': snippet,
        'score': score,
      };
}

/// 同步状态 —— 对应 Rust SyncStatusData
class SyncStatusData {
  final String status;
  final String? lastSynced;
  final int pendingChanges;

  SyncStatusData({
    required this.status,
    this.lastSynced,
    required this.pendingChanges,
  });

  Map<String, dynamic> toJson() => {
        'status': status,
        'last_synced': lastSynced,
        'pending_changes': pendingChanges,
      };
}

/// CRDT 合并结果 —— 对应 Rust MergeResult
class MergeResult {
  final int appliedCount;
  final List<String> conflicts;

  MergeResult({required this.appliedCount, required this.conflicts});

  Map<String, dynamic> toJson() =>
      {'applied_count': appliedCount, 'conflicts': conflicts};
}

/// Vault 加密数据 —— 对应 Rust VaultEncryptedDataFfi
class VaultEncryptedDataFfi {
  final String ciphertext;
  final String salt;
  final String nonce;
  final int memoryCost;
  final int timeCost;
  final int parallelism;

  VaultEncryptedDataFfi({
    required this.ciphertext,
    required this.salt,
    required this.nonce,
    required this.memoryCost,
    required this.timeCost,
    required this.parallelism,
  });
}

/// OCR 识别结果 —— 对应 Rust OcrResultFfi
class OcrResultFfi {
  final String text;
  final List<String> lines;
  final double confidence;

  OcrResultFfi({
    required this.text,
    required this.lines,
    required this.confidence,
  });
}

/// 语音转文字结果 —— 对应 Rust TranscribeResultFfi
class TranscribeResultFfi {
  final String text;
  final int durationMs;
  final List<TranscriptSegmentFfi> segments;

  TranscribeResultFfi({
    required this.text,
    required this.durationMs,
    required this.segments,
  });
}

/// 转写片段 —— 对应 Rust TranscriptSegmentFfi
class TranscriptSegmentFfi {
  final String text;
  final int startMs;
  final int endMs;

  TranscriptSegmentFfi({
    required this.text,
    required this.startMs,
    required this.endMs,
  });
}

/// 手写公式识别结果 —— 对应 Rust MathRecognitionResultFfi
class MathRecognitionResultFfi {
  final String latex;
  final double confidence;
  final List<String> alternatives;

  MathRecognitionResultFfi({
    required this.latex,
    required this.confidence,
    required this.alternatives,
  });
}

// ============================================================
// FRB API 函数 —— 对应 frb_api.rs 中的 pub fn
// codegen 运行后，这些函数体会被替换为真实的 SSE 编解码调用
// ============================================================

/// 初始化所有引擎 —— 对应 Rust init_engines()
Future<void> initEngines({required String dbPath}) async {
  // codegen 会生成: RustLib.instance.api.initEngines(dbPath: dbPath)
  // 当前为占位实现，codegen 运行后自动替换
  throw UnimplementedError('Run `flutter_rust_bridge_codegen generate` first');
}

/// 版本协商 —— 对应 Rust get_version()
Future<VersionInfo> getVersion() async =>
    throw UnimplementedError('Run flutter_rust_bridge_codegen generate first');

/// 健康检查 —— 对应 Rust health_check()
Future<HealthCheckResult> healthCheck() async =>
    throw UnimplementedError('Run flutter_rust_bridge_codegen generate first');

// ── 笔记 API ──────────────────────────────────────────────────────────

Future<NoteData> createNote({
  required String title,
  required String content,
  required String folderId,
}) async =>
    throw UnimplementedError('Run flutter_rust_bridge_codegen generate first');

Future<NoteData?> getNote({required String id}) async =>
    throw UnimplementedError('Run flutter_rust_bridge_codegen generate first');

Future<NoteData> updateNote({
  required String id,
  required String title,
  required String content,
}) async =>
    throw UnimplementedError('Run flutter_rust_bridge_codegen generate first');

Future<void> deleteNote({required String id}) async =>
    throw UnimplementedError('Run flutter_rust_bridge_codegen generate first');

Future<List<NoteData>> listNotes({required String folderId}) async =>
    throw UnimplementedError('Run flutter_rust_bridge_codegen generate first');

// ── 文件夹 API ────────────────────────────────────────────────────────

Future<FolderData> createFolder({
  required String name,
  String? parentId,
}) async =>
    throw UnimplementedError('Run flutter_rust_bridge_codegen generate first');

Future<List<FolderData>> listFolders({String? parentId}) async =>
    throw UnimplementedError('Run flutter_rust_bridge_codegen generate first');

Future<void> deleteFolder({required String id}) async =>
    throw UnimplementedError('Run flutter_rust_bridge_codegen generate first');

Future<FolderData?> getFolder({required String id}) async =>
    throw UnimplementedError('Run flutter_rust_bridge_codegen generate first');

Future<FolderData> updateFolder({
  required String id,
  required String name,
  String? parentId,
  int? sortOrder,
}) async =>
    throw UnimplementedError('Run flutter_rust_bridge_codegen generate first');

// ── 标签 API ──────────────────────────────────────────────────────────

Future<TagData> createTag({required String name}) async =>
    throw UnimplementedError('Run flutter_rust_bridge_codegen generate first');

Future<List<TagData>> listTags() async =>
    throw UnimplementedError('Run flutter_rust_bridge_codegen generate first');

Future<void> deleteTag({required String id}) async =>
    throw UnimplementedError('Run flutter_rust_bridge_codegen generate first');

// ── 编辑器 API ────────────────────────────────────────────────────────

Future<BlockData> insertBlock({
  required String noteId,
  required String blockType,
  required String content,
  int? position,
}) async =>
    throw UnimplementedError('Run flutter_rust_bridge_codegen generate first');

Future<void> updateBlock({required String id, required String content}) async =>
    throw UnimplementedError('Run flutter_rust_bridge_codegen generate first');

Future<void> deleteBlock({required String id}) async =>
    throw UnimplementedError('Run flutter_rust_bridge_codegen generate first');

Future<List<BlockData>> getBlocks({required String noteId}) async =>
    throw UnimplementedError('Run flutter_rust_bridge_codegen generate first');

// ── 搜索 API ──────────────────────────────────────────────────────────

Future<List<SearchResult>> searchNotes({
  required String query,
  int? limit,
  int? offset,
}) async =>
    throw UnimplementedError('Run flutter_rust_bridge_codegen generate first');

// ── 加密 API ──────────────────────────────────────────────────────────

Future<String> encrypt({
  required String plaintextBase64,
  required String keyBase64,
}) async =>
    throw UnimplementedError('Run flutter_rust_bridge_codegen generate first');

Future<String> decrypt({
  required String ciphertextBase64,
  required String keyBase64,
}) async =>
    throw UnimplementedError('Run flutter_rust_bridge_codegen generate first');

Future<String> deriveKey({
  required String password,
  required String saltBase64,
}) async =>
    throw UnimplementedError('Run flutter_rust_bridge_codegen generate first');

// ── 同步 API ──────────────────────────────────────────────────────────

Future<SyncStatusData> pushChanges() async =>
    throw UnimplementedError('Run flutter_rust_bridge_codegen generate first');

Future<SyncStatusData> pullChanges() async =>
    throw UnimplementedError('Run flutter_rust_bridge_codegen generate first');

Future<SyncStatusData> getSyncStatus() async =>
    throw UnimplementedError('Run flutter_rust_bridge_codegen generate first');

// ── Canvas API ────────────────────────────────────────────────────────

Future<void> canvasAddNode({
  required String canvasId,
  required String nodeJson,
}) async =>
    throw UnimplementedError('Run flutter_rust_bridge_codegen generate first');

Future<void> canvasRemoveNode({
  required String canvasId,
  required String nodeId,
}) async =>
    throw UnimplementedError('Run flutter_rust_bridge_codegen generate first');

Future<void> canvasAutoLayout({
  required String canvasId,
  required String layoutType,
}) async =>
    throw UnimplementedError('Run flutter_rust_bridge_codegen generate first');

Future<void> canvasAddEdge({
  required String canvasId,
  required String edgeJson,
}) async =>
    throw UnimplementedError('Run flutter_rust_bridge_codegen generate first');

Future<void> canvasSaveCanvas({
  required String canvasId,
  required String path,
}) async =>
    throw UnimplementedError('Run flutter_rust_bridge_codegen generate first');

Future<String> canvasLoadCanvas({required String path}) async =>
    throw UnimplementedError('Run flutter_rust_bridge_codegen generate first');

// ── 数据库 API ────────────────────────────────────────────────────────

Future<String> createDatabase({required String name}) async =>
    throw UnimplementedError('Run flutter_rust_bridge_codegen generate first');

Future<dynamic> evaluateFormula({
  required String formula,
  required String rowValues,
  required String allRows,
}) async =>
    throw UnimplementedError('Run flutter_rust_bridge_codegen generate first');

Future<String> databaseAddView({
  required String dbId,
  required String name,
  required String viewType,
}) async =>
    throw UnimplementedError('Run flutter_rust_bridge_codegen generate first');

Future<String> databaseQueryRows({required String dbId}) async =>
    throw UnimplementedError('Run flutter_rust_bridge_codegen generate first');

// ── 图谱 API ──────────────────────────────────────────────────────────

Future<String> calculateCentrality() async =>
    throw UnimplementedError('Run flutter_rust_bridge_codegen generate first');

Future<String> detectClusters() async =>
    throw UnimplementedError('Run flutter_rust_bridge_codegen generate first');

// ── 闪卡 API ──────────────────────────────────────────────────────────

Future<String> createDeck({
  required String name,
  required String description,
}) async =>
    throw UnimplementedError('Run flutter_rust_bridge_codegen generate first');

Future<String> reviewFlashcard({
  required String flashcardId,
  required int quality,
}) async =>
    throw UnimplementedError('Run flutter_rust_bridge_codegen generate first');

Future<String> getDueCards({required String deckId, int? limit}) async =>
    throw UnimplementedError('Run flutter_rust_bridge_codegen generate first');

// ── CRDT API ──────────────────────────────────────────────────────────

Future<MergeResult> crdtMerge({
  required String docId,
  required String deviceId,
  required String remoteOpsJson,
}) async =>
    throw UnimplementedError('Run flutter_rust_bridge_codegen generate first');

// ── 格式 API ──────────────────────────────────────────────────────────

Future<String> importMarkdown({required String path}) async =>
    throw UnimplementedError('Run flutter_rust_bridge_codegen generate first');

Future<void> exportMarkdown({
  required String notesJson,
  required String path,
}) async =>
    throw UnimplementedError('Run flutter_rust_bridge_codegen generate first');

// ── OCR API ───────────────────────────────────────────────────────────

Future<String> ocrRecognizeImage({required String imageBase64}) async =>
    throw UnimplementedError('Run flutter_rust_bridge_codegen generate first');

Future<OcrResultFfi> ocrRecognizeImageDetailed({
  required String imageBase64,
}) async =>
    throw UnimplementedError('Run flutter_rust_bridge_codegen generate first');

Future<void> indexOcrText({
  required String noteId,
  required String ocrText,
}) async =>
    throw UnimplementedError('Run flutter_rust_bridge_codegen generate first');

// ── Vault API ─────────────────────────────────────────────────────────

Future<VaultEncryptedDataFfi> vaultEncrypt({
  required String password,
  required String plaintext,
}) async =>
    throw UnimplementedError('Run flutter_rust_bridge_codegen generate first');

Future<String> vaultDecrypt({
  required String password,
  required VaultEncryptedDataFfi encrypted,
}) async =>
    throw UnimplementedError('Run flutter_rust_bridge_codegen generate first');

Future<bool> vaultVerifyPassword({
  required String password,
  required VaultEncryptedDataFfi encrypted,
}) async =>
    throw UnimplementedError('Run flutter_rust_bridge_codegen generate first');

// ── 语音转文字 API ────────────────────────────────────────────────────

Future<TranscribeResultFfi> transcribeAudio({
  required String audioBase64,
  required String lang,
}) async =>
    throw UnimplementedError('Run flutter_rust_bridge_codegen generate first');

// ── 手写公式识别 API ──────────────────────────────────────────────────

Future<MathRecognitionResultFfi> mathInkRecognize({
  required String strokesJson,
}) async =>
    throw UnimplementedError('Run flutter_rust_bridge_codegen generate first');
