use std::env;
use std::path::PathBuf;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR")
        .expect("CARGO_MANIFEST_DIR must be set by cargo during build");
    let config = cbindgen::Config::from_root_or_default(PathBuf::from(&crate_dir).as_path());
    cbindgen::Builder::new()
        .with_crate(crate_dir)
        .with_config(config)
        .with_language(cbindgen::Language::C)
        .with_include_guard("DEVNOTE_FFI_H")
        .with_autogen_warning("/* Auto-generated by cbindgen. Do not modify. */")
        .generate()
        .expect("Unable to generate C bindings")
        .write_to_file("devnote_ffi.h");
}
