#ifndef DEVNOTE_FFI_H
#define DEVNOTE_FFI_H

/* Auto-generated by cbindgen. Do not modify. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct FFIResponse {
  int32_t code;
  char *message;
  char *data;
} FFIResponse;

struct FFIResponse *devnote_init(void);

void devnote_destroy(struct FFIResponse *response);

void devnote_free_string(char *s);

char *devnote_ping(void);

#endif  /* DEVNOTE_FFI_H */
