#ifndef DEVNOTE_FFI_H
#define DEVNOTE_FFI_H

/* Auto-generated by cbindgen. Do not modify. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct FFIResponse {
  int32_t code;
  char *message;
  char *data;
} FFIResponse;

struct FFIResponse *devnote_init(void);

void devnote_destroy(struct FFIResponse *response);

void devnote_free_string(char *s);

char *devnote_ping(void);

char *devnote_dispatch(const char *request);

struct FFIResponse *devnote_grpc_connect(const char *server_addr);

struct FFIResponse *devnote_grpc_disconnect(void);

struct FFIResponse *devnote_grpc_dispatch(const char *method, const char *payload);

struct FFIResponse *devnote_ws_connect(const char *url);

struct FFIResponse *devnote_ws_disconnect(void);

struct FFIResponse *devnote_ws_send(const char *message);

#endif  /* DEVNOTE_FFI_H */
