[package]
name = "devnote-ipfs"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", default-features = false, features = ["json", "multipart", "stream", "rustls-tls"] }
bytes = "1"
sha2 = "0.10"
cid = "0.11"
multihash = "0.19"
async-trait = "0.1"
tracing = { workspace = true }
anyhow = { workspace = true }