import 'models/note_template.dart';

/// 内置模板库
class BuiltinTemplates {
  static List<NoteTemplate> getAll() => [
        _meetingNotes(),
        _readingNotes(),
        _projectPlan(),
        _dailyJournal(),
        _todoList(),
        _studyNotes(),
        _researchNotes(),
        _blankTemplate(),
      ];

  static NoteTemplate _meetingNotes() => NoteTemplate(
        id: 'builtin-meeting',
        name: '会议纪要',
        description: '记录会议基本信息、议程、讨论内容和行动项',
        category: TemplateCategory.meeting,
        icon: 'groups',
        isBuiltIn: true,
        blocks: [
          TemplateBlock(type: 'heading1', content: '会议纪要'),
          TemplateBlock(type: 'paragraph', content: ''),
          TemplateBlock(type: 'heading2', content: '会议信息'),
          TemplateBlock(
            type: 'tableBlock',
            content: '',
            properties: {
              'columns': ['项目', '内容'],
              'rows': [
                ['会议主题', ''],
                ['会议时间', ''],
                ['会议地点', ''],
                ['主持人', ''],
                ['参会人员', ''],
                ['记录人', ''],
              ],
            },
          ),
          TemplateBlock(type: 'paragraph', content: ''),
          TemplateBlock(type: 'heading2', content: '会议议程'),
          TemplateBlock(type: 'orderedList', content: '议程一'),
          TemplateBlock(type: 'orderedList', content: '议程二'),
          TemplateBlock(type: 'orderedList', content: '议程三'),
          TemplateBlock(type: 'paragraph', content: ''),
          TemplateBlock(type: 'heading2', content: '讨论内容'),
          TemplateBlock(type: 'paragraph', content: '在此记录讨论要点...'),
          TemplateBlock(type: 'paragraph', content: ''),
          TemplateBlock(type: 'heading2', content: '决议事项'),
          TemplateBlock(type: 'list', content: '决议一'),
          TemplateBlock(type: 'list', content: '决议二'),
          TemplateBlock(type: 'paragraph', content: ''),
          TemplateBlock(type: 'heading2', content: '行动项'),
          TemplateBlock(
            type: 'taskListBlock',
            content: '[] 任务一 — 负责人：  截止日期：',
          ),
          TemplateBlock(
            type: 'taskListBlock',
            content: '[] 任务二 — 负责人：  截止日期：',
          ),
          TemplateBlock(
            type: 'taskListBlock',
            content: '[] 任务三 — 负责人：  截止日期：',
          ),
          TemplateBlock(type: 'paragraph', content: ''),
          TemplateBlock(type: 'heading2', content: '下次会议'),
          TemplateBlock(type: 'paragraph', content: '时间：\n地点：\n议题：'),
        ],
      );

  static NoteTemplate _readingNotes() => NoteTemplate(
        id: 'builtin-reading',
        name: '读书笔记',
        description: '记录书籍信息、摘要、关键观点和个人感悟',
        category: TemplateCategory.reading,
        icon: 'menu_book',
        isBuiltIn: true,
        blocks: [
          TemplateBlock(type: 'heading1', content: '读书笔记'),
          TemplateBlock(type: 'paragraph', content: ''),
          TemplateBlock(type: 'heading2', content: '书籍信息'),
          TemplateBlock(
            type: 'tableBlock',
            content: '',
            properties: {
              'columns': ['项目', '内容'],
              'rows': [
                ['书名', ''],
                ['作者', ''],
                ['出版社', ''],
                ['出版日期', ''],
                ['阅读日期', ''],
                ['评分', '⭐⭐⭐⭐⭐'],
              ],
            },
          ),
          TemplateBlock(type: 'paragraph', content: ''),
          TemplateBlock(type: 'heading2', content: '内容摘要'),
          TemplateBlock(type: 'paragraph', content: '用一段话概括全书核心内容...'),
          TemplateBlock(type: 'paragraph', content: ''),
          TemplateBlock(type: 'heading2', content: '关键观点'),
          TemplateBlock(type: 'list', content: '观点一：'),
          TemplateBlock(type: 'list', content: '观点二：'),
          TemplateBlock(type: 'list', content: '观点三：'),
          TemplateBlock(type: 'paragraph', content: ''),
          TemplateBlock(type: 'heading2', content: '精彩摘录'),
          TemplateBlock(type: 'quote', content: '摘录原文精彩段落...'),
          TemplateBlock(type: 'paragraph', content: ''),
          TemplateBlock(type: 'heading2', content: '个人感悟'),
          TemplateBlock(type: 'paragraph', content: '记录个人思考和启发...'),
          TemplateBlock(type: 'paragraph', content: ''),
          TemplateBlock(type: 'heading2', content: '行动项'),
          TemplateBlock(type: 'taskListBlock', content: '[] 如何将书中知识应用到实践中？'),
        ],
      );

  static NoteTemplate _projectPlan() => NoteTemplate(
        id: 'builtin-project',
        name: '项目计划',
        description: '项目目标、里程碑、任务分解和风险评估',
        category: TemplateCategory.project,
        icon: 'assignment',
        isBuiltIn: true,
        blocks: [
          TemplateBlock(type: 'heading1', content: '项目计划'),
          TemplateBlock(type: 'paragraph', content: ''),
          TemplateBlock(type: 'heading2', content: '项目概述'),
          TemplateBlock(type: 'paragraph', content: '项目名称：\n项目目标：\n项目周期：'),
          TemplateBlock(type: 'paragraph', content: ''),
          TemplateBlock(type: 'heading2', content: '项目团队'),
          TemplateBlock(
            type: 'tableBlock',
            content: '',
            properties: {
              'columns': ['角色', '姓名', '职责'],
              'rows': [
                ['项目经理', '', ''],
                ['开发', '', ''],
                ['测试', '', ''],
                ['设计', '', ''],
              ],
            },
          ),
          TemplateBlock(type: 'paragraph', content: ''),
          TemplateBlock(type: 'heading2', content: '里程碑'),
          TemplateBlock(
            type: 'tableBlock',
            content: '',
            properties: {
              'columns': ['里程碑', '日期', '交付物'],
              'rows': [
                ['需求确认', '', ''],
                ['设计完成', '', ''],
                ['开发完成', '', ''],
                ['测试完成', '', ''],
                ['上线发布', '', ''],
              ],
            },
          ),
          TemplateBlock(type: 'paragraph', content: ''),
          TemplateBlock(type: 'heading2', content: '任务分解'),
          TemplateBlock(type: 'taskListBlock', content: '[] 需求分析'),
          TemplateBlock(type: 'taskListBlock', content: '[] 架构设计'),
          TemplateBlock(type: 'taskListBlock', content: '[] 核心开发'),
          TemplateBlock(type: 'taskListBlock', content: '[] 单元测试'),
          TemplateBlock(type: 'taskListBlock', content: '[] 集成测试'),
          TemplateBlock(type: 'taskListBlock', content: '[] 部署上线'),
          TemplateBlock(type: 'paragraph', content: ''),
          TemplateBlock(type: 'heading2', content: '风险评估'),
          TemplateBlock(type: 'list', content: '风险一：  应对措施：'),
          TemplateBlock(type: 'list', content: '风险二：  应对措施：'),
        ],
      );

  static NoteTemplate _dailyJournal() => NoteTemplate(
        id: 'builtin-daily',
        name: '每日笔记',
        description: '每日工作记录、反思和明日计划',
        category: TemplateCategory.daily,
        icon: 'calendar_today',
        isBuiltIn: true,
        blocks: [
          TemplateBlock(type: 'heading1', content: '每日笔记'),
          TemplateBlock(type: 'paragraph', content: ''),
          TemplateBlock(type: 'heading2', content: '今日完成'),
          TemplateBlock(type: 'taskListBlock', content: '[] '),
          TemplateBlock(type: 'taskListBlock', content: '[] '),
          TemplateBlock(type: 'taskListBlock', content: '[] '),
          TemplateBlock(type: 'paragraph', content: ''),
          TemplateBlock(type: 'heading2', content: '今日收获'),
          TemplateBlock(type: 'paragraph', content: '记录今天的学习和思考...'),
          TemplateBlock(type: 'paragraph', content: ''),
          TemplateBlock(type: 'heading2', content: '遇到的问题'),
          TemplateBlock(type: 'list', content: '问题一：'),
          TemplateBlock(type: 'paragraph', content: ''),
          TemplateBlock(type: 'heading2', content: '明日计划'),
          TemplateBlock(type: 'taskListBlock', content: '[] '),
          TemplateBlock(type: 'taskListBlock', content: '[] '),
        ],
      );

  static NoteTemplate _todoList() => NoteTemplate(
        id: 'builtin-todo',
        name: '待办清单',
        description: '简洁的待办事项清单',
        category: TemplateCategory.todo,
        icon: 'checklist',
        isBuiltIn: true,
        blocks: [
          TemplateBlock(type: 'heading1', content: '待办清单'),
          TemplateBlock(type: 'paragraph', content: ''),
          TemplateBlock(type: 'heading2', content: '今日待办'),
          TemplateBlock(type: 'taskListBlock', content: '[] '),
          TemplateBlock(type: 'taskListBlock', content: '[] '),
          TemplateBlock(type: 'taskListBlock', content: '[] '),
          TemplateBlock(type: 'paragraph', content: ''),
          TemplateBlock(type: 'heading2', content: '本周待办'),
          TemplateBlock(type: 'taskListBlock', content: '[] '),
          TemplateBlock(type: 'taskListBlock', content: '[] '),
          TemplateBlock(type: 'paragraph', content: ''),
          TemplateBlock(type: 'heading2', content: '长期目标'),
          TemplateBlock(type: 'taskListBlock', content: '[] '),
        ],
      );

  static NoteTemplate _studyNotes() => NoteTemplate(
        id: 'builtin-study',
        name: '学习笔记',
        description: '课程/技术学习笔记，含知识点和代码示例',
        category: TemplateCategory.study,
        icon: 'school',
        isBuiltIn: true,
        blocks: [
          TemplateBlock(type: 'heading1', content: '学习笔记'),
          TemplateBlock(type: 'paragraph', content: ''),
          TemplateBlock(type: 'heading2', content: '学习主题'),
          TemplateBlock(type: 'paragraph', content: ''),
          TemplateBlock(type: 'heading2', content: '核心概念'),
          TemplateBlock(type: 'list', content: '概念一：'),
          TemplateBlock(type: 'list', content: '概念二：'),
          TemplateBlock(type: 'paragraph', content: ''),
          TemplateBlock(type: 'heading2', content: '代码示例'),
          TemplateBlock(
            type: 'codeBlock',
            content: '// 在此输入代码',
            properties: {'language': 'dart'},
          ),
          TemplateBlock(type: 'paragraph', content: ''),
          TemplateBlock(type: 'heading2', content: '要点总结'),
          TemplateBlock(type: 'list', content: '要点一'),
          TemplateBlock(type: 'list', content: '要点二'),
          TemplateBlock(type: 'paragraph', content: ''),
          TemplateBlock(type: 'heading2', content: '疑问与后续'),
          TemplateBlock(type: 'list', content: '疑问一：'),
          TemplateBlock(type: 'taskListBlock', content: '[] 后续学习计划'),
        ],
      );

  static NoteTemplate _researchNotes() => NoteTemplate(
        id: 'builtin-research',
        name: '研究记录',
        description: '研究课题记录，含文献、方法和结论',
        category: TemplateCategory.research,
        icon: 'science',
        isBuiltIn: true,
        blocks: [
          TemplateBlock(type: 'heading1', content: '研究记录'),
          TemplateBlock(type: 'paragraph', content: ''),
          TemplateBlock(type: 'heading2', content: '研究课题'),
          TemplateBlock(type: 'paragraph', content: ''),
          TemplateBlock(type: 'heading2', content: '研究背景'),
          TemplateBlock(type: 'paragraph', content: ''),
          TemplateBlock(type: 'heading2', content: '研究方法'),
          TemplateBlock(type: 'orderedList', content: '步骤一'),
          TemplateBlock(type: 'orderedList', content: '步骤二'),
          TemplateBlock(type: 'paragraph', content: ''),
          TemplateBlock(type: 'heading2', content: '数据与分析'),
          TemplateBlock(type: 'paragraph', content: ''),
          TemplateBlock(type: 'heading2', content: '参考文献'),
          TemplateBlock(type: 'list', content: '[1] '),
          TemplateBlock(type: 'list', content: '[2] '),
          TemplateBlock(type: 'paragraph', content: ''),
          TemplateBlock(type: 'heading2', content: '结论'),
          TemplateBlock(type: 'paragraph', content: ''),
        ],
      );

  static NoteTemplate _blankTemplate() => NoteTemplate(
        id: 'builtin-blank',
        name: '空白笔记',
        description: '从空白开始',
        category: TemplateCategory.other,
        icon: 'note_add',
        isBuiltIn: true,
        blocks: [
          TemplateBlock(type: 'heading1', content: '新笔记'),
          TemplateBlock(type: 'paragraph', content: ''),
        ],
      );
}
