[package]
name = "devnote-qt"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
devnote-observe = { workspace = true }
tracing = { workspace = true }
libloading = "0.8"
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
parking_lot = "0.12"