[package]
name = "devnote-persistence"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
devnote-core = { workspace = true }
devnote-crypto = { workspace = true }
devnote-observe = { workspace = true }
tracing = { workspace = true }
rusqlite = { version = "0.32", features = ["bundled"] }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
sha2 = "0.10"
base64 = "0.22"
devnote-ipfs = { path = "../devnote-ipfs", optional = true }

[features]
ipfs = ["devnote-ipfs"]
