[package]
name = "devnote-plugin"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[features]
default = []
wasm = ["wasmtime"]

[dependencies]
devnote-observe = { workspace = true }
tracing = { workspace = true }
wasmtime = { version = "29", optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
